# Generated by Django 4.0.7 on 2026-07-16 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0005_remove_digitalinventoryreservation_digital_res_state_valid_and_more'),
        ('financial_core', '0003_enforce_financial_state_constraints'),
        ('shop', '0020_stockreservation_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('safe_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantAccountVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_key', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('owner_key', models.CharField(max_length=128)),
                ('credential_reference', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('new_requests_enabled', models.BooleanField(default=False)),
                ('recovery_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentObligationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('checkout_placement', 'CHECKOUT_PLACEMENT'), ('legacy_order_adoption', 'LEGACY_ORDER_ADOPTION')], max_length=32)),
                ('source_model', models.CharField(max_length=100)),
                ('source_object_id', models.CharField(max_length=128)),
                ('source_field', models.CharField(max_length=100)),
                ('source_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('source_unit', models.CharField(choices=[('IRR', 'IRR'), ('IRT', 'IRT')], max_length=16)),
                ('canonical_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('canonical_currency', models.CharField(default='IRR', max_length=3)),
                ('bridge_version', models.CharField(max_length=64)),
                ('evidence_fingerprint', models.CharField(max_length=64, unique=True)),
                ('commercial_snapshot_hash', models.CharField(max_length=64)),
                ('commerce_authority', models.CharField(max_length=30)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCapabilityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('adapter_key', models.CharField(max_length=64)),
                ('adapter_contract_version', models.CharField(max_length=32)),
                ('provider_unit', models.CharField(choices=[('IRR', 'IRR'), ('IRT', 'IRT')], max_length=16)),
                ('conversion_policy_version', models.CharField(max_length=64)),
                ('supported_operations', models.JSONField(default=list)),
                ('supports_request_idempotency', models.BooleanField(default=False)),
                ('supports_lookup', models.BooleanField(default=False)),
                ('callback_authentication', models.CharField(choices=[('none', 'NONE'), ('shared_secret', 'SHARED_SECRET'), ('asymmetric_signature', 'ASYMMETRIC_SIGNATURE'), ('mtls', 'MTLS')], default='none', max_length=32)),
                ('verification_semantics', models.CharField(choices=[('required', 'REQUIRED'), ('request_response_final', 'REQUEST_RESPONSE_FINAL')], default='required', max_length=32)),
                ('finality_window_seconds', models.PositiveIntegerField()),
                ('authority_expiry_seconds', models.PositiveIntegerField()),
                ('supports_refund', models.BooleanField(default=False)),
                ('supports_void', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=False)),
                ('new_requests_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderRequestClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('claim_token', models.UUIDField(editable=False, unique=True)),
                ('claimed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderRequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('customer_action_required', 'CUSTOMER_ACTION_REQUIRED'), ('accepted_pending', 'ACCEPTED_PENDING'), ('confirmed_success', 'CONFIRMED_SUCCESS'), ('confirmed_decline', 'CONFIRMED_DECLINE'), ('confirmed_canceled', 'CONFIRMED_CANCELED'), ('confirmed_expired', 'CONFIRMED_EXPIRED'), ('no_effect_retryable', 'NO_EFFECT_RETRYABLE'), ('outcome_unknown', 'OUTCOME_UNKNOWN'), ('security_failure', 'SECURITY_FAILURE'), ('configuration_failure', 'CONFIGURATION_FAILURE'), ('protocol_failure', 'PROTOCOL_FAILURE')], max_length=32)),
                ('claim_token', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='fin_tx_provider_unit_irr',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='adapter_contract_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='causation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='claim_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_conversion_policy_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_idempotency_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(('provider_unit__in', ['IRR', 'IRT'])), name='fin_tx_provider_unit_valid'),
        ),
        migrations.AddField(
            model_name='providerrequestresult',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_results', to='financial_core.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='providerrequestclaim',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_claims', to='financial_core.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='providercapabilityversion',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capability_versions', to='financial_core.providerdefinition'),
        ),
        migrations.AddField(
            model_name='paymentobligationsource',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_source', to='financial_core.payment'),
        ),
        migrations.AddField(
            model_name='merchantaccountversion',
            name='capability_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_accounts', to='financial_core.providercapabilityversion'),
        ),
        migrations.AddField(
            model_name='merchantaccountversion',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_accounts', to='financial_core.providerdefinition'),
        ),
        migrations.AddConstraint(
            model_name='financialoutboxmessage',
            constraint=models.CheckConstraint(check=models.Q(('topic', ''), _negated=True), name='fin_outbox_topic_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='financialoutboxmessage',
            constraint=models.CheckConstraint(check=models.Q(('aggregate_type', ''), _negated=True), name='fin_outbox_aggregate_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='financialoutboxmessage',
            constraint=models.CheckConstraint(check=models.Q(('aggregate_id', ''), _negated=True), name='fin_outbox_aggregate_id_nonempty'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='capability_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='financial_core.providercapabilityversion'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='merchant_account_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='financial_core.merchantaccountversion'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='capability_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='financial_core.providercapabilityversion'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_account_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='financial_core.merchantaccountversion'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('merchant_account_version__isnull', False)), fields=('merchant_account_version', 'merchant_reference'), name='fin_tx_account_version_merchant_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='providerrequestresult',
            constraint=models.CheckConstraint(check=models.Q(('outcome__in', ['customer_action_required', 'accepted_pending', 'confirmed_success', 'confirmed_decline', 'confirmed_canceled', 'confirmed_expired', 'no_effect_retryable', 'outcome_unknown', 'security_failure', 'configuration_failure', 'protocol_failure'])), name='fin_request_result_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerrequestresult',
            constraint=models.CheckConstraint(check=models.Q(('request_fingerprint', ''), _negated=True), name='fin_request_result_fingerprint_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providerrequestresult',
            constraint=models.CheckConstraint(check=models.Q(('evidence_hash', ''), _negated=True), name='fin_request_result_evidence_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providerrequestclaim',
            constraint=models.UniqueConstraint(fields=('transaction', 'sequence'), name='fin_request_claim_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='providerrequestclaim',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gt', 0)), name='fin_request_claim_sequence_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='providerrequestclaim',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', django.db.models.expressions.F('claimed_at'))), name='fin_request_claim_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='providercapabilityversion',
            constraint=models.UniqueConstraint(fields=('provider', 'version'), name='fin_provider_capability_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='providercapabilityversion',
            constraint=models.CheckConstraint(check=models.Q(('version__gt', 0)), name='fin_provider_capability_version_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='providercapabilityversion',
            constraint=models.CheckConstraint(check=models.Q(('provider_unit__in', ['IRR', 'IRT'])), name='fin_provider_unit_valid'),
        ),
        migrations.AddConstraint(
            model_name='providercapabilityversion',
            constraint=models.CheckConstraint(check=models.Q(('adapter_key', ''), _negated=True), name='fin_provider_adapter_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providercapabilityversion',
            constraint=models.CheckConstraint(check=models.Q(('adapter_contract_version', ''), _negated=True), name='fin_provider_adapter_version_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providercapabilityversion',
            constraint=models.CheckConstraint(check=models.Q(('conversion_policy_version', ''), _negated=True), name='fin_provider_conversion_version_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligationsource',
            constraint=models.UniqueConstraint(fields=('source_model', 'source_object_id', 'source_field'), name='fin_obligation_source_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligationsource',
            constraint=models.CheckConstraint(check=models.Q(('source_amount__gt', 0)), name='fin_obligation_source_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligationsource',
            constraint=models.CheckConstraint(check=models.Q(('canonical_amount__gt', 0)), name='fin_obligation_canonical_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligationsource',
            constraint=models.CheckConstraint(check=models.Q(('canonical_currency', 'IRR')), name='fin_obligation_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligationsource',
            constraint=models.CheckConstraint(check=models.Q(('source_unit__in', ['IRR', 'IRT'])), name='fin_obligation_unit_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligationsource',
            constraint=models.CheckConstraint(check=models.Q(('bridge_version', ''), _negated=True), name='fin_obligation_bridge_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligationsource',
            constraint=models.CheckConstraint(check=models.Q(('commercial_snapshot_hash', ''), _negated=True), name='fin_obligation_snapshot_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='merchantaccountversion',
            constraint=models.UniqueConstraint(fields=('provider', 'account_key', 'version'), name='fin_merchant_account_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='merchantaccountversion',
            constraint=models.CheckConstraint(check=models.Q(('version__gt', 0)), name='fin_merchant_account_version_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='merchantaccountversion',
            constraint=models.CheckConstraint(check=models.Q(('account_key', ''), _negated=True), name='fin_merchant_account_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='merchantaccountversion',
            constraint=models.CheckConstraint(check=models.Q(('owner_key', ''), _negated=True), name='fin_merchant_owner_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='merchantaccountversion',
            constraint=models.CheckConstraint(check=models.Q(('credential_reference', ''), _negated=True), name='fin_merchant_credential_ref_nonempty'),
        ),
    ]
