# Generated by Django 4.0.7 on 2026-07-16 12:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('financial_core', '0004_financialoutboxmessage_merchantaccountversion_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('created', 'requires_customer_action', 'processing', 'succeeded', 'outcome_unknown', 'review'))), fields=('payment',), name='fin_one_blocking_attempt_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('capability_version__isnull', True), ('merchant_account_version__isnull', True)), models.Q(('capability_version__isnull', False), ('merchant_account_version__isnull', False)), _connector='OR'), name='fin_attempt_provider_versions_together'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligationsource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('canonical_amount', django.db.models.expressions.F('source_amount')), ('source_unit', 'IRR')), models.Q(('canonical_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('source_amount'), '*', django.db.models.expressions.Value(10))), ('source_unit', 'IRT')), _connector='OR'), name='fin_obligation_conversion_exact'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('provider_amount', django.db.models.expressions.F('amount')), ('provider_unit', 'IRR')), models.Q(('amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('provider_amount'), '*', django.db.models.expressions.Value(10))), ('provider_unit', 'IRT')), _connector='OR'), name='fin_tx_provider_amount_exact'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('capability_version__isnull', True), ('merchant_account_version__isnull', True)), models.Q(('capability_version__isnull', False), ('merchant_account_version__isnull', False), models.Q(('request_fingerprint', ''), _negated=True), models.Q(('adapter_contract_version', ''), _negated=True), models.Q(('provider_conversion_policy_version', ''), _negated=True)), _connector='OR'), name='fin_tx_provider_versions_consistent'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(('capability_version__isnull', True), models.Q(('claim_expires_at__isnull', False), ('claim_token__isnull', False), ('claimed_at__isnull', False), ('status', 'requesting')), models.Q(('status', 'requesting'), _negated=True), _connector='OR'), name='fin_tx_request_claim_present'),
        ),
    ]
