# Generated by Django 4.0.7 on 2026-07-16 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial_core', '0007_postgresql_c2a_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_key_hint', models.CharField(max_length=64)),
                ('adapter_version_hint', models.CharField(max_length=32)),
                ('account_hint_hash', models.CharField(blank=True, max_length=64)),
                ('http_method', models.CharField(max_length=8)),
                ('content_type', models.CharField(max_length=100)),
                ('body_length', models.PositiveIntegerField()),
                ('raw_envelope_hash', models.CharField(max_length=64)),
                ('header_evidence', models.JSONField(blank=True, default=dict)),
                ('source_network_hash', models.CharField(blank=True, max_length=64)),
                ('authentication_status', models.CharField(choices=[('authenticated', 'AUTHENTICATED'), ('unauthenticated_hint', 'UNAUTHENTICATED_HINT'), ('invalid', 'INVALID')], max_length=32)),
                ('authentication_strength', models.CharField(choices=[('none', 'NONE'), ('shared_secret', 'SHARED_SECRET'), ('asymmetric_signature', 'ASYMMETRIC_SIGNATURE'), ('mtls', 'MTLS')], default='none', max_length=32)),
                ('authentication_method', models.CharField(blank=True, max_length=64)),
                ('authentication_version', models.CharField(blank=True, max_length=32)),
                ('authentication_evidence_hash', models.CharField(blank=True, max_length=64)),
                ('signing_key_reference_hash', models.CharField(blank=True, max_length=64)),
                ('replay_window_status', models.CharField(choices=[('valid', 'VALID'), ('expired', 'EXPIRED'), ('not_supported', 'NOT_SUPPORTED')], max_length=24)),
                ('processing_status', models.CharField(choices=[('normalized', 'NORMALIZED'), ('duplicate', 'DUPLICATE'), ('quarantined', 'QUARANTINED'), ('security_rejected', 'SECURITY_REJECTED')], max_length=24)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('quarantine_reason', models.CharField(blank=True, max_length=64)),
                ('safe_reason_code', models.CharField(blank=True, max_length=64)),
                ('delivery_idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('retention_until', models.DateTimeField()),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('adapter_contract_version', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(blank=True, max_length=128)),
                ('canonical_envelope_hash', models.CharField(max_length=64)),
                ('merchant_reference', models.CharField(blank=True, max_length=128)),
                ('provider_authority', models.CharField(blank=True, max_length=128)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('operation_type_hint', models.CharField(blank=True, max_length=16)),
                ('provider_amount_hint', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('provider_unit_hint', models.CharField(blank=True, max_length=16)),
                ('normalized_hint', models.CharField(max_length=64)),
                ('provider_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('authentication_strength', models.CharField(choices=[('none', 'NONE'), ('shared_secret', 'SHARED_SECRET'), ('asymmetric_signature', 'ASYMMETRIC_SIGNATURE'), ('mtls', 'MTLS')], max_length=32)),
                ('deduplication_identity', models.CharField(max_length=64, unique=True)),
                ('resolution_status', models.CharField(choices=[('verification_required', 'VERIFICATION_REQUIRED'), ('quarantined', 'QUARANTINED'), ('contradictory', 'CONTRADICTORY')], max_length=32)),
                ('quarantine_reason', models.CharField(blank=True, max_length=64)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='providercapabilityversion',
            name='not_found_is_final_unpaid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VerificationWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('work_type', models.CharField(choices=[('verify_after_callback', 'VERIFY_AFTER_CALLBACK'), ('verify_after_browser_hint', 'VERIFY_AFTER_BROWSER_HINT'), ('poll_pending_operation', 'POLL_PENDING_OPERATION'), ('verify_unknown_outcome', 'VERIFY_UNKNOWN_OUTCOME'), ('retry_provider_query', 'RETRY_PROVIDER_QUERY'), ('escalate_unknown_outcome', 'ESCALATE_UNKNOWN_OUTCOME'), ('apply_verified_funds', 'APPLY_VERIFIED_FUNDS')], max_length=40)),
                ('deterministic_identity', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('claimed', 'CLAIMED'), ('waiting', 'WAITING'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_classification', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('provider_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_work_items', to='financial_core.providerevent')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_work_items', to='financial_core.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('claim_token', models.UUIDField(editable=False, unique=True)),
                ('claimed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_claims', to='financial_core.paymenttransaction')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='financial_core.verificationworkitem')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('trigger_source', models.CharField(choices=[('callback', 'CALLBACK'), ('browser_hint', 'BROWSER_HINT'), ('request_result', 'REQUEST_RESULT'), ('poll', 'POLL'), ('unknown_outcome', 'UNKNOWN_OUTCOME'), ('reconciliation', 'RECONCILIATION'), ('admin_retry', 'ADMIN_RETRY')], max_length=32)),
                ('adapter_contract_version', models.CharField(max_length=32)),
                ('merchant_reference', models.CharField(max_length=128)),
                ('provider_authority', models.CharField(blank=True, max_length=128)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('operation_type', models.CharField(choices=[('sale', 'SALE'), ('authorize', 'AUTHORIZE'), ('capture', 'CAPTURE'), ('void', 'VOID'), ('refund', 'REFUND'), ('chargeback', 'CHARGEBACK')], max_length=16)),
                ('requested_provider_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('requested_provider_unit', models.CharField(choices=[('IRR', 'IRR'), ('IRT', 'IRT')], max_length=16)),
                ('observed_provider_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('observed_provider_unit', models.CharField(blank=True, max_length=16)),
                ('canonical_allocation_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('canonical_currency', models.CharField(default='IRR', max_length=3)),
                ('normalized_outcome', models.CharField(choices=[('confirmed_success', 'CONFIRMED_SUCCESS'), ('confirmed_decline', 'CONFIRMED_DECLINE'), ('confirmed_canceled', 'CONFIRMED_CANCELED'), ('confirmed_expired', 'CONFIRMED_EXPIRED'), ('pending', 'PENDING'), ('no_effect_retryable', 'NO_EFFECT_RETRYABLE'), ('outcome_unknown', 'OUTCOME_UNKNOWN'), ('mismatch', 'MISMATCH'), ('contradictory_evidence', 'CONTRADICTORY_EVIDENCE'), ('security_failure', 'SECURITY_FAILURE'), ('configuration_failure', 'CONFIGURATION_FAILURE'), ('protocol_failure', 'PROTOCOL_FAILURE'), ('not_found_final', 'NOT_FOUND_FINAL')], max_length=40)),
                ('normalized_financial_effect', models.CharField(choices=[('paid', 'PAID'), ('unpaid', 'UNPAID'), ('none', 'NONE'), ('unknown', 'UNKNOWN')], max_length=16)),
                ('finality', models.CharField(choices=[('final', 'FINAL'), ('non_final', 'NON_FINAL'), ('unknown', 'UNKNOWN')], max_length=16)),
                ('provider_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('transport_classification', models.CharField(choices=[('success', 'SUCCESS'), ('timeout', 'TIMEOUT'), ('network_failure', 'NETWORK_FAILURE'), ('protocol_failure', 'PROTOCOL_FAILURE'), ('not_executed', 'NOT_EXECUTED')], max_length=24)),
                ('evidence_hash', models.CharField(max_length=64)),
                ('request_evidence_reference', models.CharField(blank=True, max_length=128)),
                ('response_evidence_reference', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application_state', models.CharField(choices=[('unapplied', 'UNAPPLIED'), ('applied_unpaid', 'APPLIED_UNPAID'), ('applied_blocking_success', 'APPLIED_BLOCKING_SUCCESS'), ('review_required', 'REVIEW_REQUIRED'), ('superseded', 'SUPERSEDED')], max_length=32)),
                ('error_classification', models.CharField(blank=True, max_length=64)),
                ('retryable', models.BooleanField(default=False)),
                ('result_idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('result_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='financial_core.providercapabilityversion')),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='financial_core.verificationclaim')),
                ('merchant_account_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='financial_core.merchantaccountversion')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='financial_core.providerdefinition')),
                ('provider_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='financial_core.providerevent')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='financial_core.paymenttransaction')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='financial_core.verificationworkitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderReferenceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_reference', models.CharField(max_length=128)),
                ('allocation_fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant_account_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_reference_allocations', to='financial_core.merchantaccountversion')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider_reference_allocation', to='financial_core.paymenttransaction')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_reference_allocations', to='financial_core.verification')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderEventReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkage_fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('callback_receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event_link', to='financial_core.callbackreceipt')),
                ('provider_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_links', to='financial_core.providerevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='providerevent',
            name='capability_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='financial_core.providercapabilityversion'),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='merchant_account_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='financial_core.merchantaccountversion'),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='financial_core.providerdefinition'),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='financial_core.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='callbackreceipt',
            name='capability_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='callback_receipts', to='financial_core.providercapabilityversion'),
        ),
        migrations.AddField(
            model_name='callbackreceipt',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_deliveries', to='financial_core.callbackreceipt'),
        ),
        migrations.AddField(
            model_name='callbackreceipt',
            name='merchant_account_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='callback_receipts', to='financial_core.merchantaccountversion'),
        ),
        migrations.AddField(
            model_name='callbackreceipt',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='callback_receipts', to='financial_core.providerdefinition'),
        ),
        migrations.AddIndex(
            model_name='verificationworkitem',
            index=models.Index(fields=['status', 'next_attempt_at'], name='fin_work_due'),
        ),
        migrations.AddConstraint(
            model_name='verificationworkitem',
            constraint=models.CheckConstraint(check=models.Q(('attempt_count__lte', django.db.models.expressions.F('max_attempts'))), name='fin_work_attempts_bounded'),
        ),
        migrations.AddConstraint(
            model_name='verificationworkitem',
            constraint=models.CheckConstraint(check=models.Q(('max_attempts__gt', 0)), name='fin_work_max_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='verificationworkitem',
            constraint=models.CheckConstraint(check=models.Q(('work_type__in', ['verify_after_callback', 'verify_after_browser_hint', 'poll_pending_operation', 'verify_unknown_outcome', 'retry_provider_query', 'escalate_unknown_outcome', 'apply_verified_funds'])), name='fin_work_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationworkitem',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'claimed', 'waiting', 'completed', 'canceled'])), name='fin_work_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationworkitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('claim_expires_at__isnull', False), ('claim_token__isnull', False), ('claimed_at__isnull', False), ('completed_at__isnull', True), ('status', 'claimed')), models.Q(('claim_expires_at__isnull', True), ('claim_token__isnull', True), ('claimed_at__isnull', True), ('completed_at__isnull', True), ('status__in', ('pending', 'waiting'))), models.Q(('claim_expires_at__isnull', True), ('claim_token__isnull', True), ('claimed_at__isnull', True), ('completed_at__isnull', False), ('status__in', ('completed', 'canceled'))), _connector='OR'), name='fin_work_lease_state_consistent'),
        ),
        migrations.AddConstraint(
            model_name='verificationclaim',
            constraint=models.UniqueConstraint(fields=('work_item', 'sequence'), name='fin_ver_claim_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='verificationclaim',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gt', 0)), name='fin_ver_claim_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='verificationclaim',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', django.db.models.expressions.F('claimed_at'))), name='fin_ver_claim_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationclaim',
            constraint=models.CheckConstraint(check=models.Q(('request_fingerprint', ''), _negated=True), name='fin_ver_claim_hash_nonempty'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['transaction', 'normalized_outcome'], name='fin_ver_tx_outcome'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['application_state', 'verified_at'], name='fin_ver_application'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.UniqueConstraint(fields=('transaction', 'sequence'), name='fin_ver_tx_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gt', 0)), name='fin_ver_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('requested_provider_amount__gt', 0)), name='fin_ver_requested_positive'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('canonical_allocation_amount__gt', 0)), name='fin_ver_canonical_positive'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('canonical_currency', 'IRR')), name='fin_ver_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('observed_provider_amount__isnull', True), ('observed_provider_unit', '')), models.Q(('observed_provider_amount__gt', 0), ('observed_provider_unit__in', ['IRR', 'IRT'])), _connector='OR'), name='fin_ver_observed_money_together'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('application_state', 'applied_blocking_success'), ('finality', 'final'), ('normalized_financial_effect', 'paid'), ('normalized_outcome', 'confirmed_success'), ('observed_provider_amount__isnull', False), models.Q(('provider_reference', ''), _negated=True)), models.Q(('normalized_outcome', 'confirmed_success'), _negated=True), _connector='OR'), name='fin_ver_success_evidence_complete'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('evidence_hash', ''), _negated=True), name='fin_ver_evidence_hash_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.CheckConstraint(check=models.Q(('result_fingerprint', ''), _negated=True), name='fin_ver_result_hash_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providerreferenceallocation',
            constraint=models.UniqueConstraint(fields=('merchant_account_version', 'provider_reference'), name='fin_provider_reference_account_uniq'),
        ),
        migrations.AddConstraint(
            model_name='providerreferenceallocation',
            constraint=models.CheckConstraint(check=models.Q(('provider_reference', ''), _negated=True), name='fin_provider_reference_nonempty'),
        ),
        migrations.AddIndex(
            model_name='providerevent',
            index=models.Index(fields=['merchant_account_version', 'provider_event_id'], name='fin_provider_event_external'),
        ),
        migrations.AddIndex(
            model_name='providerevent',
            index=models.Index(fields=['merchant_reference', 'created_at'], name='fin_provider_event_merchant'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.CheckConstraint(check=models.Q(('canonical_envelope_hash', ''), _negated=True), name='fin_provider_event_hash_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.CheckConstraint(check=models.Q(('normalized_hint', ''), _negated=True), name='fin_provider_event_hint_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.CheckConstraint(check=models.Q(('resolution_status__in', ['verification_required', 'quarantined', 'contradictory'])), name='fin_provider_event_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.CheckConstraint(check=models.Q(('provider_amount_hint__isnull', True), ('provider_amount_hint__gt', 0), _connector='OR'), name='fin_provider_event_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('provider_amount_hint__isnull', True), ('provider_unit_hint', '')), models.Q(('provider_amount_hint__isnull', False), ('provider_unit_hint__in', ['IRR', 'IRT'])), _connector='OR'), name='fin_provider_event_money_together'),
        ),
        migrations.AddIndex(
            model_name='callbackreceipt',
            index=models.Index(fields=['provider', 'raw_envelope_hash'], name='fin_cb_provider_envelope'),
        ),
        migrations.AddIndex(
            model_name='callbackreceipt',
            index=models.Index(fields=['processing_status', 'received_at'], name='fin_cb_status_received'),
        ),
        migrations.AddConstraint(
            model_name='callbackreceipt',
            constraint=models.CheckConstraint(check=models.Q(('body_length__gte', 0)), name='fin_cb_body_length_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='callbackreceipt',
            constraint=models.CheckConstraint(check=models.Q(('raw_envelope_hash', ''), _negated=True), name='fin_cb_envelope_hash_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='callbackreceipt',
            constraint=models.CheckConstraint(check=models.Q(('http_method', ''), _negated=True), name='fin_cb_method_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='callbackreceipt',
            constraint=models.CheckConstraint(check=models.Q(('authentication_status__in', ['authenticated', 'unauthenticated_hint', 'invalid'])), name='fin_cb_auth_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='callbackreceipt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('authentication_status', 'authenticated'), _negated=True), models.Q(('authentication_evidence_hash', ''), _negated=True), _connector='OR'), name='fin_cb_authenticated_evidence'),
        ),
        migrations.AddConstraint(
            model_name='callbackreceipt',
            constraint=models.CheckConstraint(check=models.Q(('replay_window_status__in', ['valid', 'expired', 'not_supported'])), name='fin_cb_replay_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='callbackreceipt',
            constraint=models.CheckConstraint(check=models.Q(('processing_status__in', ['normalized', 'duplicate', 'quarantined', 'security_rejected'])), name='fin_cb_processing_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='callbackreceipt',
            constraint=models.CheckConstraint(check=models.Q(('retention_until__gt', django.db.models.expressions.F('received_at'))), name='fin_cb_retention_after_receipt'),
        ),
    ]
