# Generated by Django 4.0.7 on 2026-07-16 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial_core', '0009_postgresql_c2b1_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialFinalizationWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('finalizer_version', models.CharField(max_length=64)),
                ('deterministic_identity', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('claimed', 'CLAIMED'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=12)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_classification', models.CharField(blank=True, max_length=64)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_reference', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('application_idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('application_fingerprint', models.CharField(max_length=64)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('applied_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptAccountingPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('policy_key', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('active_for_new_applications', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='reviewcase',
            name='fin_review_reason_valid',
        ),
        migrations.AddField(
            model_name='verification',
            name='evidence_basis',
            field=models.CharField(choices=[('none', 'NONE'), ('server_to_server', 'SERVER_TO_SERVER'), ('authenticated_settlement', 'AUTHENTICATED_SETTLEMENT')], default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewcase',
            name='reason',
            field=models.CharField(choices=[('provider_state_unclear', 'PROVIDER_STATE_UNCLEAR'), ('paid_finalization_pending', 'PAID_FINALIZATION_PENDING'), ('amount_mismatch', 'AMOUNT_MISMATCH'), ('currency_mismatch', 'CURRENCY_MISMATCH'), ('duplicate_provider_reference', 'DUPLICATE_PROVIDER_REFERENCE'), ('late_payment', 'LATE_PAYMENT'), ('inventory_conflict', 'INVENTORY_CONFLICT'), ('reconciliation_mismatch', 'RECONCILIATION_MISMATCH'), ('fraud_risk', 'FRAUD_RISK'), ('invariant_violation', 'INVARIANT_VIOLATION'), ('verified_funds_application_failed', 'VERIFIED_FUNDS_APPLICATION_FAILED'), ('provider_receipt_journal_failed', 'PROVIDER_RECEIPT_JOURNAL_FAILED'), ('paid_pending_finalization', 'PAID_PENDING_FINALIZATION'), ('duplicate_financial_allocation', 'DUPLICATE_FINANCIAL_ALLOCATION'), ('overpayment', 'OVERPAYMENT'), ('accounting_policy_missing', 'ACCOUNTING_POLICY_MISSING'), ('financial_invariant_violation', 'FINANCIAL_INVARIANT_VIOLATION')], db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='verification',
            name='application_state',
            field=models.CharField(choices=[('unapplied', 'UNAPPLIED'), ('applied_unpaid', 'APPLIED_UNPAID'), ('applied_blocking_success', 'APPLIED_BLOCKING_SUCCESS'), ('review_required', 'REVIEW_REQUIRED'), ('superseded', 'SUPERSEDED'), ('financially_applied', 'FINANCIALLY_APPLIED')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='reviewcase',
            constraint=models.CheckConstraint(check=models.Q(('reason__in', ['provider_state_unclear', 'paid_finalization_pending', 'amount_mismatch', 'currency_mismatch', 'duplicate_provider_reference', 'late_payment', 'inventory_conflict', 'reconciliation_mismatch', 'fraud_risk', 'invariant_violation', 'verified_funds_application_failed', 'provider_receipt_journal_failed', 'paid_pending_finalization', 'duplicate_financial_allocation', 'overpayment', 'accounting_policy_missing', 'financial_invariant_violation'])), name='fin_review_reason_valid'),
        ),
        migrations.AddField(
            model_name='receiptaccountingpolicyversion',
            name='customer_unapplied_funds_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_unapplied_receipt_policies', to='financial_core.financialaccount'),
        ),
        migrations.AddField(
            model_name='receiptaccountingpolicyversion',
            name='merchant_account_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_accounting_policies', to='financial_core.merchantaccountversion'),
        ),
        migrations.AddField(
            model_name='receiptaccountingpolicyversion',
            name='provider_clearing_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_receipt_policies', to='financial_core.financialaccount'),
        ),
        migrations.AddField(
            model_name='financialallocation',
            name='accounting_policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_allocations', to='financial_core.receiptaccountingpolicyversion'),
        ),
        migrations.AddField(
            model_name='financialallocation',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_allocations', to='financial_core.paymentattempt'),
        ),
        migrations.AddField(
            model_name='financialallocation',
            name='journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_allocation', to='financial_core.journalentry'),
        ),
        migrations.AddField(
            model_name='financialallocation',
            name='merchant_account_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_allocations', to='financial_core.merchantaccountversion'),
        ),
        migrations.AddField(
            model_name='financialallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_allocations', to='financial_core.payment'),
        ),
        migrations.AddField(
            model_name='financialallocation',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_allocation', to='financial_core.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='financialallocation',
            name='verification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_allocation', to='financial_core.verification'),
        ),
        migrations.AddField(
            model_name='commercialfinalizationworkitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalization_work_items', to='financial_core.payment'),
        ),
        migrations.AddConstraint(
            model_name='receiptaccountingpolicyversion',
            constraint=models.UniqueConstraint(fields=('merchant_account_version', 'policy_key', 'version'), name='fin_receipt_policy_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receiptaccountingpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('active_for_new_applications', True)), fields=('merchant_account_version',), name='fin_one_active_receipt_policy'),
        ),
        migrations.AddConstraint(
            model_name='receiptaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('version__gt', 0)), name='fin_receipt_policy_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('policy_key', ''), _negated=True), name='fin_receipt_policy_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='receiptaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_receipt_policy_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='receiptaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('provider_clearing_account', django.db.models.expressions.F('customer_unapplied_funds_account')), _negated=True), name='fin_receipt_policy_accounts_distinct'),
        ),
        migrations.AddIndex(
            model_name='financialallocation',
            index=models.Index(fields=['payment', 'applied_at'], name='fin_allocation_payment_time'),
        ),
        migrations.AddConstraint(
            model_name='financialallocation',
            constraint=models.UniqueConstraint(fields=('merchant_account_version', 'provider_reference'), name='fin_allocation_provider_reference_uniq'),
        ),
        migrations.AddConstraint(
            model_name='financialallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='fin_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financialallocation',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_allocation_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='financialallocation',
            constraint=models.CheckConstraint(check=models.Q(('provider_reference', ''), _negated=True), name='fin_allocation_provider_ref_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='financialallocation',
            constraint=models.CheckConstraint(check=models.Q(('application_fingerprint', ''), _negated=True), name='fin_allocation_hash_nonempty'),
        ),
        migrations.AddIndex(
            model_name='commercialfinalizationworkitem',
            index=models.Index(fields=['status', 'next_attempt_at'], name='fin_finalization_work_due'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalizationworkitem',
            constraint=models.UniqueConstraint(fields=('payment', 'finalizer_version'), name='fin_finalization_work_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalizationworkitem',
            constraint=models.CheckConstraint(check=models.Q(('finalizer_version', ''), _negated=True), name='fin_finalizer_version_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalizationworkitem',
            constraint=models.CheckConstraint(check=models.Q(('max_attempts__gt', 0)), name='fin_finalization_max_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalizationworkitem',
            constraint=models.CheckConstraint(check=models.Q(('attempt_count__lte', django.db.models.expressions.F('max_attempts'))), name='fin_finalization_attempts_bounded'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalizationworkitem',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'claimed', 'completed', 'canceled'])), name='fin_finalization_work_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalizationworkitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('claim_expires_at__isnull', False), ('claim_token__isnull', False), ('claimed_at__isnull', False), ('completed_at__isnull', True), ('status', 'claimed')), models.Q(('claim_expires_at__isnull', True), ('claim_token__isnull', True), ('claimed_at__isnull', True), ('completed_at__isnull', True), ('status', 'pending')), models.Q(('claim_expires_at__isnull', True), ('claim_token__isnull', True), ('claimed_at__isnull', True), ('completed_at__isnull', False), ('status__in', ('completed', 'canceled'))), _connector='OR'), name='fin_finalization_work_state_consistent'),
        ),
    ]
