# Generated by Django 4.0.7 on 2026-07-17 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_stockreservation_order_and_more'),
        ('digital_products', '0005_remove_digitalinventoryreservation_digital_res_state_valid_and_more'),
        ('product', '0020_deliveredversion_product_commerce_authority'),
        ('financial_core', '0011_postgresql_verified_funds_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAccountingPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('policy_key', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('commerce_authority', models.CharField(max_length=30)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('active_for_new_finalizations', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('merchandise_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('shipping_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('commerce_authority', models.CharField(max_length=30)),
                ('finalizer_version', models.CharField(max_length=64)),
                ('application_idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('application_fingerprint', models.CharField(max_length=64)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('finalized_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalFulfillmentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('fulfillment_method', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardFulfillmentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='reviewcase',
            name='fin_review_reason_valid',
        ),
        migrations.AlterField(
            model_name='reviewcase',
            name='reason',
            field=models.CharField(choices=[('provider_state_unclear', 'PROVIDER_STATE_UNCLEAR'), ('paid_finalization_pending', 'PAID_FINALIZATION_PENDING'), ('amount_mismatch', 'AMOUNT_MISMATCH'), ('currency_mismatch', 'CURRENCY_MISMATCH'), ('duplicate_provider_reference', 'DUPLICATE_PROVIDER_REFERENCE'), ('late_payment', 'LATE_PAYMENT'), ('inventory_conflict', 'INVENTORY_CONFLICT'), ('reconciliation_mismatch', 'RECONCILIATION_MISMATCH'), ('fraud_risk', 'FRAUD_RISK'), ('invariant_violation', 'INVARIANT_VIOLATION'), ('verified_funds_application_failed', 'VERIFIED_FUNDS_APPLICATION_FAILED'), ('provider_receipt_journal_failed', 'PROVIDER_RECEIPT_JOURNAL_FAILED'), ('paid_pending_finalization', 'PAID_PENDING_FINALIZATION'), ('duplicate_financial_allocation', 'DUPLICATE_FINANCIAL_ALLOCATION'), ('overpayment', 'OVERPAYMENT'), ('accounting_policy_missing', 'ACCOUNTING_POLICY_MISSING'), ('financial_invariant_violation', 'FINANCIAL_INVARIANT_VIOLATION'), ('commercial_finalization_failed', 'COMMERCIAL_FINALIZATION_FAILED'), ('commercial_journal_failed', 'COMMERCIAL_JOURNAL_FAILED')], db_index=True, max_length=48),
        ),
        migrations.AddConstraint(
            model_name='reviewcase',
            constraint=models.CheckConstraint(check=models.Q(('reason__in', ['provider_state_unclear', 'paid_finalization_pending', 'amount_mismatch', 'currency_mismatch', 'duplicate_provider_reference', 'late_payment', 'inventory_conflict', 'reconciliation_mismatch', 'fraud_risk', 'invariant_violation', 'verified_funds_application_failed', 'provider_receipt_journal_failed', 'paid_pending_finalization', 'duplicate_financial_allocation', 'overpayment', 'accounting_policy_missing', 'financial_invariant_violation', 'commercial_finalization_failed', 'commercial_journal_failed'])), name='fin_review_reason_valid'),
        ),
        migrations.AddField(
            model_name='standardfulfillmentobligation',
            name='finalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_fulfillment_obligations', to='financial_core.commercialfinalization'),
        ),
        migrations.AddField(
            model_name='standardfulfillmentobligation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_fulfillment_obligations', to='shop.order'),
        ),
        migrations.AddField(
            model_name='standardfulfillmentobligation',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='standard_fulfillment_obligation', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='standardfulfillmentobligation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_fulfillment_obligations', to='product.product'),
        ),
        migrations.AddField(
            model_name='standardfulfillmentobligation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_obligations', to='shop.stockreservation'),
        ),
        migrations.AddField(
            model_name='digitalfulfillmentobligation',
            name='checkout_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='digital_fulfillment_obligation', to='shop.checkoutline'),
        ),
        migrations.AddField(
            model_name='digitalfulfillmentobligation',
            name='finalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_fulfillment_obligations', to='financial_core.commercialfinalization'),
        ),
        migrations.AddField(
            model_name='digitalfulfillmentobligation',
            name='inventory_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_obligations', to='digital_products.inventorypool'),
        ),
        migrations.AddField(
            model_name='digitalfulfillmentobligation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_fulfillment_obligations', to='shop.order'),
        ),
        migrations.AddField(
            model_name='digitalfulfillmentobligation',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='digital_fulfillment_obligation', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='digitalfulfillmentobligation',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_obligation', to='digital_products.digitalinventoryreservation'),
        ),
        migrations.AddField(
            model_name='commercialfinalization',
            name='accounting_policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalizations', to='financial_core.commercialaccountingpolicyversion'),
        ),
        migrations.AddField(
            model_name='commercialfinalization',
            name='journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_finalization', to='financial_core.journalentry'),
        ),
        migrations.AddField(
            model_name='commercialfinalization',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_finalization', to='shop.order'),
        ),
        migrations.AddField(
            model_name='commercialfinalization',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_finalization', to='financial_core.payment'),
        ),
        migrations.AddField(
            model_name='commercialaccountingpolicyversion',
            name='customer_unapplied_funds_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_deferred_policies', to='financial_core.financialaccount'),
        ),
        migrations.AddField(
            model_name='commercialaccountingpolicyversion',
            name='merchandise_revenue_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_merchandise_policies', to='financial_core.financialaccount'),
        ),
        migrations.AddField(
            model_name='commercialaccountingpolicyversion',
            name='shipping_revenue_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_shipping_policies', to='financial_core.financialaccount'),
        ),
        migrations.AddConstraint(
            model_name='standardfulfillmentobligation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='fin_standard_fulfillment_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='digitalfulfillmentobligation',
            constraint=models.CheckConstraint(check=models.Q(('quantity', 1)), name='fin_digital_fulfillment_qty_one'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalization',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='fin_commercial_final_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalization',
            constraint=models.CheckConstraint(check=models.Q(('merchandise_amount__gte', 0)), name='fin_commercial_merch_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalization',
            constraint=models.CheckConstraint(check=models.Q(('shipping_amount__gte', 0)), name='fin_commercial_shipping_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalization',
            constraint=models.CheckConstraint(check=models.Q(('amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('merchandise_amount'), '+', django.db.models.expressions.F('shipping_amount')))), name='fin_commercial_amount_components'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalization',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_commercial_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalization',
            constraint=models.CheckConstraint(check=models.Q(('finalizer_version', ''), _negated=True), name='fin_commercial_finalizer_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalization',
            constraint=models.CheckConstraint(check=models.Q(('application_fingerprint', ''), _negated=True), name='fin_commercial_hash_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='commercialaccountingpolicyversion',
            constraint=models.UniqueConstraint(fields=('policy_key', 'version', 'commerce_authority'), name='fin_commercial_policy_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='commercialaccountingpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('active_for_new_finalizations', True)), fields=('commerce_authority',), name='fin_one_active_commercial_policy'),
        ),
        migrations.AddConstraint(
            model_name='commercialaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('version__gt', 0)), name='fin_commercial_policy_version_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='commercialaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('policy_key', ''), _negated=True), name='fin_commercial_policy_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='commercialaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_commercial_policy_irr'),
        ),
        migrations.AddConstraint(
            model_name='commercialaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('commerce_authority__in', ('standard_commerce', 'digital_products'))), name='fin_commercial_policy_authority_valid'),
        ),
    ]
