# Generated by Django 4.0.7 on 2026-07-17 11:07

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('financial_core', '0013_postgresql_commercial_finalizer_guards'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commercialaccountingpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('customer_unapplied_funds_account', django.db.models.expressions.F('merchandise_revenue_account')), _negated=True), models.Q(('customer_unapplied_funds_account', django.db.models.expressions.F('shipping_revenue_account')), _negated=True), models.Q(('merchandise_revenue_account', django.db.models.expressions.F('shipping_revenue_account')), _negated=True)), name='fin_commercial_policy_accounts_distinct'),
        ),
    ]
