# Generated by Django 4.0.7 on 2026-07-19 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_stockreservation_order_and_more'),
        ('digital_products', '0011_postgresql_fulfillment_integrity_hardening'),
        ('product', '0020_deliveredversion_product_commerce_authority'),
        ('financial_core', '0019_postgresql_funds_recognition_handoff_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalInventoryCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reservation_set_digest', models.CharField(max_length=64)),
                ('pre_quantity', models.PositiveBigIntegerField()),
                ('committed_quantity', models.PositiveBigIntegerField()),
                ('post_quantity', models.PositiveBigIntegerField()),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardInventoryCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reservation_set_digest', models.CharField(max_length=64)),
                ('pre_quantity', models.PositiveBigIntegerField()),
                ('committed_quantity', models.PositiveBigIntegerField()),
                ('post_quantity', models.PositiveBigIntegerField()),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='financialevent',
            name='fin_event_actor_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='reviewcase',
            name='fin_review_actor_type_valid',
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='actor_type',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('system', 'SYSTEM'), ('provider', 'PROVIDER'), ('admin', 'ADMIN'), ('support', 'SUPPORT'), ('reconciliation', 'RECONCILIATION'), ('commercial_recovery', 'COMMERCIAL_RECOVERY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewcase',
            name='opened_by_type',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('system', 'SYSTEM'), ('provider', 'PROVIDER'), ('admin', 'ADMIN'), ('support', 'SUPPORT'), ('reconciliation', 'RECONCILIATION'), ('commercial_recovery', 'COMMERCIAL_RECOVERY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_review_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='actor_type',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('system', 'SYSTEM'), ('provider', 'PROVIDER'), ('admin', 'ADMIN'), ('support', 'SUPPORT'), ('reconciliation', 'RECONCILIATION'), ('commercial_recovery', 'COMMERCIAL_RECOVERY')], default='admin', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='reviewaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor__isnull', True), ('actor_type', 'system')), models.Q(models.Q(('actor_type', 'system'), _negated=True), ('actor__isnull', False)), _connector='OR'), name='fin_review_action_actor_coherent'),
        ),
        migrations.AddConstraint(
            model_name='financialevent',
            constraint=models.CheckConstraint(check=models.Q(('actor_type__in', ['customer', 'system', 'provider', 'admin', 'support', 'reconciliation', 'commercial_recovery'])), name='fin_event_actor_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='reviewcase',
            constraint=models.CheckConstraint(check=models.Q(('opened_by_type__in', ['customer', 'system', 'provider', 'admin', 'support', 'reconciliation', 'commercial_recovery'])), name='fin_review_actor_type_valid'),
        ),
        migrations.AddField(
            model_name='standardinventorycommitment',
            name='finalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_inventory_commitments', to='financial_core.commercialfinalization'),
        ),
        migrations.AddField(
            model_name='standardinventorycommitment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_inventory_commitments', to='shop.order'),
        ),
        migrations.AddField(
            model_name='standardinventorycommitment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_inventory_commitments', to='product.product'),
        ),
        migrations.AddField(
            model_name='digitalinventorycommitment',
            name='finalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_inventory_commitments', to='financial_core.commercialfinalization'),
        ),
        migrations.AddField(
            model_name='digitalinventorycommitment',
            name='inventory_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_inventory_commitments', to='digital_products.inventorypool'),
        ),
        migrations.AddField(
            model_name='digitalinventorycommitment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_inventory_commitments', to='shop.order'),
        ),
        migrations.AddConstraint(
            model_name='standardinventorycommitment',
            constraint=models.UniqueConstraint(fields=('finalization', 'product'), name='fin_standard_commit_final_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='standardinventorycommitment',
            constraint=models.CheckConstraint(check=models.Q(('committed_quantity__gt', 0)), name='fin_standard_commit_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='standardinventorycommitment',
            constraint=models.CheckConstraint(check=models.Q(('pre_quantity', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('post_quantity'), '+', django.db.models.expressions.F('committed_quantity')))), name='fin_standard_commit_quantity_delta'),
        ),
        migrations.AddConstraint(
            model_name='standardinventorycommitment',
            constraint=models.CheckConstraint(check=models.Q(('reservation_set_digest', ''), _negated=True), name='fin_standard_commit_digest_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='digitalinventorycommitment',
            constraint=models.UniqueConstraint(fields=('finalization', 'inventory_pool'), name='fin_digital_commit_final_pool_uniq'),
        ),
        migrations.AddConstraint(
            model_name='digitalinventorycommitment',
            constraint=models.CheckConstraint(check=models.Q(('committed_quantity__gt', 0)), name='fin_digital_commit_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='digitalinventorycommitment',
            constraint=models.CheckConstraint(check=models.Q(('pre_quantity', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('post_quantity'), '+', django.db.models.expressions.F('committed_quantity')))), name='fin_digital_commit_quantity_delta'),
        ),
        migrations.AddConstraint(
            model_name='digitalinventorycommitment',
            constraint=models.CheckConstraint(check=models.Q(('reservation_set_digest', ''), _negated=True), name='fin_digital_commit_digest_nonempty'),
        ),
    ]
