# Generated by Django 4.0.7 on 2026-07-22 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_stockreservation_order_and_more'),
        ('financial_core', '0021_postgresql_api08_finalization_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsiderationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('allocated_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('standalone_selling_price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('standalone_selling_price_denominator', models.DecimalField(decimal_places=0, max_digits=20)),
                ('allocation_method', models.CharField(choices=[('direct_frozen_price', 'DIRECT_FROZEN_PRICE'), ('relative_standalone_selling_price', 'RELATIVE_STANDALONE_SELLING_PRICE')], max_length=48)),
                ('discount_classification', models.CharField(max_length=64)),
                ('shipping_classification', models.CharField(max_length=64)),
                ('rounding_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('remainder_recipient', models.BooleanField(default=False)),
                ('allocation_contract_version', models.CharField(max_length=64)),
                ('allocation_fingerprint', models.CharField(max_length=64, unique=True)),
                ('application_idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consideration_allocations', to='financial_core.financialaccount')),
                ('finalization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consideration_allocations', to='financial_core.commercialfinalization')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('obligation_key', models.CharField(max_length=128)),
                ('obligation_type', models.CharField(choices=[('physical_good', 'PHYSICAL_GOOD'), ('digital_access_installation', 'DIGITAL_ACCESS_INSTALLATION'), ('shipping', 'SHIPPING'), ('installation_service', 'INSTALLATION_SERVICE'), ('repair_service', 'REPAIR_SERVICE'), ('customization_service', 'CUSTOMIZATION_SERVICE'), ('combined_bundle', 'COMBINED_BUNDLE')], max_length=40)),
                ('commerce_authority', models.CharField(max_length=30)),
                ('satisfaction_pattern', models.CharField(choices=[('point_in_time', 'POINT_IN_TIME'), ('over_time', 'OVER_TIME')], max_length=20)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('quantity_basis', models.PositiveBigIntegerField(default=1)),
                ('fulfillment_required', models.BooleanField(default=True)),
                ('obligation_contract_version', models.CharField(max_length=64)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_obligations', to='financial_core.commercialfinalization')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_obligations', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('policy_key', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('policy_contract_version', models.CharField(max_length=64)),
                ('commerce_authority', models.CharField(max_length=30)),
                ('obligation_type', models.CharField(choices=[('physical_good', 'PHYSICAL_GOOD'), ('digital_access_installation', 'DIGITAL_ACCESS_INSTALLATION'), ('shipping', 'SHIPPING'), ('installation_service', 'INSTALLATION_SERVICE'), ('repair_service', 'REPAIR_SERVICE'), ('customization_service', 'CUSTOMIZATION_SERVICE'), ('combined_bundle', 'COMBINED_BUNDLE')], max_length=40)),
                ('satisfaction_pattern', models.CharField(choices=[('point_in_time', 'POINT_IN_TIME'), ('over_time', 'OVER_TIME')], max_length=20)),
                ('evidence_contract_version', models.CharField(max_length=64)),
                ('progress_measurement_method', models.CharField(choices=[('none', 'NONE'), ('output', 'OUTPUT'), ('input', 'INPUT')], default='none', max_length=16)),
                ('allocation_method', models.CharField(choices=[('direct_frozen_price', 'DIRECT_FROZEN_PRICE'), ('relative_standalone_selling_price', 'RELATIVE_STANDALONE_SELLING_PRICE')], max_length=48)),
                ('principal_agent_classification', models.CharField(choices=[('principal', 'PRINCIPAL'), ('agent_net', 'AGENT_NET')], max_length=16)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('shipping_treatment', models.CharField(max_length=64)),
                ('rounding_policy', models.CharField(max_length=64)),
                ('maximum_recognition_basis', models.CharField(max_length=64)),
                ('policy_fingerprint', models.CharField(max_length=64, unique=True)),
                ('active_for_new_obligations', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_liability_policies', to='financial_core.financialaccount')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_revenue_policies', to='financial_core.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evidence_classification', models.CharField(choices=[('point_in_time_satisfied', 'POINT_IN_TIME_SATISFIED'), ('progress_recorded', 'PROGRESS_RECORDED'), ('contradictory', 'CONTRADICTORY'), ('corrective', 'CORRECTIVE'), ('resolution', 'RESOLUTION')], max_length=32)),
                ('source_domain', models.CharField(max_length=64)),
                ('source_aggregate_type', models.CharField(max_length=64)),
                ('source_aggregate_id', models.CharField(max_length=128)),
                ('source_event_id', models.CharField(max_length=128)),
                ('source_event_version', models.PositiveBigIntegerField()),
                ('evidence_contract_version', models.CharField(max_length=64)),
                ('satisfied_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('progress_numerator', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('progress_denominator', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('evidence_authority', models.CharField(choices=[('system', 'SYSTEM'), ('staff', 'STAFF'), ('customer', 'CUSTOMER'), ('carrier', 'CARRIER'), ('reconciliation', 'RECONCILIATION')], max_length=20)),
                ('actor_type', models.CharField(choices=[('customer', 'CUSTOMER'), ('system', 'SYSTEM'), ('provider', 'PROVIDER'), ('admin', 'ADMIN'), ('support', 'SUPPORT'), ('reconciliation', 'RECONCILIATION'), ('commercial_recovery', 'COMMERCIAL_RECOVERY')], max_length=24)),
                ('actor_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_evidence_hash', models.CharField(max_length=64)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contradicts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contradictions', to='financial_core.satisfactionevidence')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='financial_core.satisfactionevidence')),
                ('digital_fulfillment_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_evidence', to='financial_core.digitalfulfillmentobligation')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_evidence', to='financial_core.performanceobligation')),
                ('standard_fulfillment_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_evidence', to='financial_core.standardfulfillmentobligation')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueRecognitionWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('recognize_satisfaction', 'RECOGNIZE_SATISFACTION'), ('correct_recognition', 'CORRECT_RECOGNITION')], max_length=32)),
                ('evidence_set_digest', models.CharField(max_length=64)),
                ('recognition_contract_version', models.CharField(max_length=64)),
                ('recognition_period_key', models.CharField(max_length=64)),
                ('cumulative_target_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('deterministic_identity', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('claimed', 'CLAIMED'), ('waiting', 'WAITING'), ('completed', 'COMPLETED'), ('review_required', 'REVIEW_REQUIRED'), ('canceled', 'CANCELED')], default='pending', max_length=24)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claim_owner', models.CharField(blank=True, max_length=128)),
                ('claim_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_classification', models.CharField(blank=True, max_length=64)),
                ('safe_result', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_work_items', to='financial_core.performanceobligation')),
                ('recognition_policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_work_items', to='financial_core.recognitionpolicyversion')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('effect', models.CharField(choices=[('earn', 'EARN'), ('reverse', 'REVERSE')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('cumulative_net_recognized_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('evidence_set_digest', models.CharField(max_length=64)),
                ('recognition_period_key', models.CharField(max_length=64)),
                ('correction_reason', models.CharField(blank=True, max_length=256)),
                ('command_contract_version', models.CharField(max_length=64)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('application_fingerprint', models.CharField(max_length=64, unique=True)),
                ('actor_type', models.CharField(choices=[('customer', 'CUSTOMER'), ('system', 'SYSTEM'), ('provider', 'PROVIDER'), ('admin', 'ADMIN'), ('support', 'SUPPORT'), ('reconciliation', 'RECONCILIATION'), ('commercial_recovery', 'COMMERCIAL_RECOVERY')], max_length=24)),
                ('actor_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recognized_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consideration_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_recognitions', to='financial_core.considerationallocation')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='financial_core.revenuerecognition')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_recognition', to='financial_core.journalentry')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_recognitions', to='financial_core.performanceobligation')),
                ('recognition_policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_recognitions', to='financial_core.recognitionpolicyversion')),
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_recognition', to='financial_core.revenuerecognitionworkitem')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceObligationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_key', models.CharField(max_length=128)),
                ('component_type', models.CharField(choices=[('order_line', 'ORDER_LINE'), ('shipping', 'SHIPPING'), ('fulfillment', 'FULFILLMENT')], max_length=24)),
                ('source_authority_identity', models.CharField(max_length=128)),
                ('quantity', models.PositiveBigIntegerField()),
                ('commercial_snapshot_digest', models.CharField(max_length=64)),
                ('sequence', models.PositiveIntegerField()),
                ('component_contract_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligation_components', to='shop.checkoutline')),
                ('digital_fulfillment_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_components', to='financial_core.digitalfulfillmentobligation')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='financial_core.performanceobligation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_components', to='shop.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligation_components', to='shop.orderitem')),
                ('standard_fulfillment_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_components', to='financial_core.standardfulfillmentobligation')),
            ],
        ),
        migrations.AddField(
            model_name='performanceobligation',
            name='recognition_policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_obligations', to='financial_core.recognitionpolicyversion'),
        ),
        migrations.AddField(
            model_name='considerationallocation',
            name='obligation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consideration_allocation', to='financial_core.performanceobligation'),
        ),
        migrations.AddField(
            model_name='considerationallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consideration_allocations', to='financial_core.payment'),
        ),
        migrations.AddField(
            model_name='considerationallocation',
            name='recognition_policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consideration_allocations', to='financial_core.recognitionpolicyversion'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionevidence',
            constraint=models.UniqueConstraint(fields=('obligation', 'source_domain', 'source_aggregate_type', 'source_aggregate_id', 'source_event_id', 'source_event_version', 'source_evidence_hash'), name='fin_satisfaction_source_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionevidence',
            constraint=models.CheckConstraint(check=models.Q(('source_event_version__gt', 0)), name='fin_satisfaction_event_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionevidence',
            constraint=models.CheckConstraint(check=models.Q(('satisfied_quantity__gte', 0)), name='fin_satisfaction_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionevidence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('progress_denominator__isnull', True), ('progress_numerator__isnull', True)), models.Q(('progress_denominator__gt', 0), ('progress_denominator__isnull', False), ('progress_numerator__gte', 0), ('progress_numerator__isnull', False), ('progress_numerator__lte', django.db.models.expressions.F('progress_denominator'))), _connector='OR'), name='fin_satisfaction_progress_coherent'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionevidence',
            constraint=models.CheckConstraint(check=models.Q(('standard_fulfillment_obligation__isnull', False), ('digital_fulfillment_obligation__isnull', False), _negated=True), name='fin_satisfaction_one_fulfillment'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionevidence',
            constraint=models.CheckConstraint(check=models.Q(('corrects__isnull', False), ('contradicts__isnull', False), _negated=True), name='fin_satisfaction_one_lineage_link'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionevidence',
            constraint=models.CheckConstraint(check=models.Q(('source_evidence_hash', ''), _negated=True), name='fin_satisfaction_hash_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='satisfactionevidence',
            constraint=models.CheckConstraint(check=models.Q(('request_fingerprint', ''), _negated=True), name='fin_satisfaction_request_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.UniqueConstraint(fields=('obligation', 'purpose', 'evidence_set_digest', 'recognition_period_key', 'cumulative_target_amount'), name='fin_recognition_work_scope_uniq'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.CheckConstraint(check=models.Q(('evidence_set_digest', ''), _negated=True), name='fin_rec_work_evidence_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.CheckConstraint(check=models.Q(('deterministic_identity', ''), _negated=True), name='fin_rec_work_identity_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.CheckConstraint(check=models.Q(('recognition_contract_version', ''), _negated=True), name='fin_rec_work_contract_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.CheckConstraint(check=models.Q(('recognition_period_key', ''), _negated=True), name='fin_rec_work_period_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.CheckConstraint(check=models.Q(('cumulative_target_amount__gte', 0)), name='fin_rec_work_target_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.CheckConstraint(check=models.Q(('max_attempts__gt', 0)), name='fin_rec_work_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.CheckConstraint(check=models.Q(('attempt_count__lte', django.db.models.expressions.F('max_attempts'))), name='fin_rec_work_attempt_bound'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognitionworkitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('claim_expires_at__isnull', True), ('claim_owner', ''), ('claim_token__isnull', True), ('claimed_at__isnull', True), ('completed_at__isnull', True), ('status__in', ('pending', 'waiting'))), models.Q(('claim_expires_at__isnull', False), ('claim_owner__gt', ''), ('claim_token__isnull', False), ('claimed_at__isnull', False), ('completed_at__isnull', True), ('status', 'claimed')), models.Q(('claim_expires_at__isnull', True), ('claim_owner', ''), ('claim_token__isnull', True), ('claimed_at__isnull', True), ('completed_at__isnull', False), ('status__in', ('completed', 'review_required', 'canceled'))), _connector='OR'), name='fin_recognition_work_state_coherent'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognition',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='fin_revenue_recognition_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognition',
            constraint=models.CheckConstraint(check=models.Q(('cumulative_net_recognized_amount__gte', 0)), name='fin_revenue_recognition_cumulative_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognition',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_revenue_recognition_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognition',
            constraint=models.CheckConstraint(check=models.Q(('evidence_set_digest', ''), _negated=True), name='fin_revenue_recognition_evidence_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognition',
            constraint=models.CheckConstraint(check=models.Q(('command_contract_version', ''), _negated=True), name='fin_revenue_recognition_contract_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognition',
            constraint=models.CheckConstraint(check=models.Q(('application_fingerprint', ''), _negated=True), name='fin_revenue_recognition_fingerprint_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognition',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor_id__isnull', True), ('actor_type', 'system')), models.Q(('actor_id__isnull', False), ('actor_type', 'reconciliation')), _connector='OR'), name='fin_revenue_recognition_actor_authorized'),
        ),
        migrations.AddConstraint(
            model_name='revenuerecognition',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('correction_reason', ''), ('corrects__isnull', True), ('effect', 'earn')), models.Q(('corrects__isnull', False), ('effect', 'reverse'), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='fin_revenue_recognition_effect_coherent'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.UniqueConstraint(fields=('policy_key', 'version'), name='fin_rec_policy_key_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('active_for_new_obligations', True)), fields=('commerce_authority', 'obligation_type'), name='fin_one_active_recognition_policy'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('version__gt', 0)), name='fin_rec_policy_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_rec_policy_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('policy_key', ''), _negated=True), name='fin_rec_policy_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('policy_contract_version', ''), _negated=True), name='fin_rec_policy_contract_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('evidence_contract_version', ''), _negated=True), name='fin_rec_evidence_contract_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('policy_fingerprint', ''), _negated=True), name='fin_rec_policy_fingerprint_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(('contract_liability_account', django.db.models.expressions.F('revenue_account')), _negated=True), name='fin_rec_policy_accounts_distinct'),
        ),
        migrations.AddConstraint(
            model_name='recognitionpolicyversion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('progress_measurement_method', 'none'), ('satisfaction_pattern', 'point_in_time')), models.Q(('progress_measurement_method__in', ('input', 'output')), ('satisfaction_pattern', 'over_time')), _connector='OR'), name='fin_rec_policy_progress_coherent'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligationcomponent',
            constraint=models.UniqueConstraint(fields=('obligation', 'component_key'), name='fin_perf_component_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligationcomponent',
            constraint=models.UniqueConstraint(fields=('obligation', 'sequence'), name='fin_perf_component_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligationcomponent',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='fin_perf_component_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligationcomponent',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gt', 0)), name='fin_perf_component_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligationcomponent',
            constraint=models.CheckConstraint(check=models.Q(('component_key', ''), _negated=True), name='fin_perf_component_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligationcomponent',
            constraint=models.CheckConstraint(check=models.Q(('source_authority_identity', ''), _negated=True), name='fin_perf_component_source_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligationcomponent',
            constraint=models.CheckConstraint(check=models.Q(('commercial_snapshot_digest', ''), _negated=True), name='fin_perf_component_digest_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligationcomponent',
            constraint=models.CheckConstraint(check=models.Q(('standard_fulfillment_obligation__isnull', False), ('digital_fulfillment_obligation__isnull', False), _negated=True), name='fin_perf_component_one_fulfillment'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligation',
            constraint=models.UniqueConstraint(fields=('finalization', 'obligation_key'), name='fin_perf_obligation_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligation',
            constraint=models.CheckConstraint(check=models.Q(('obligation_key', ''), _negated=True), name='fin_perf_obligation_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligation',
            constraint=models.CheckConstraint(check=models.Q(('quantity_basis__gt', 0)), name='fin_perf_obligation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligation',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_perf_obligation_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='performanceobligation',
            constraint=models.CheckConstraint(check=models.Q(('obligation_contract_version', ''), _negated=True), name='fin_perf_obligation_contract_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='considerationallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_amount__gte', 0)), name='fin_consideration_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='considerationallocation',
            constraint=models.CheckConstraint(check=models.Q(('standalone_selling_price__gte', 0)), name='fin_consideration_ssp_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='considerationallocation',
            constraint=models.CheckConstraint(check=models.Q(('standalone_selling_price_denominator__gt', 0)), name='fin_consideration_denominator_positive'),
        ),
        migrations.AddConstraint(
            model_name='considerationallocation',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_consideration_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='considerationallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocation_fingerprint', ''), _negated=True), name='fin_consideration_fingerprint_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='considerationallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocation_contract_version', ''), _negated=True), name='fin_consideration_contract_nonempty'),
        ),
    ]
