# Generated by Django 4.0.7 on 2026-07-22 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_core', '0023_postgresql_revenue_recognition_foundation_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialfinalization',
            name='contract_liability_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_liability_finalizations', to='financial_core.financialaccount'),
        ),
        migrations.AddField(
            model_name='commercialfinalization',
            name='recognition_accounting_contract',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='commercialfinalization',
            name='recognition_policy_set_digest',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='commercialfinalization',
            name='accounting_policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalizations', to='financial_core.commercialaccountingpolicyversion'),
        ),
        migrations.AddConstraint(
            model_name='commercialfinalization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('accounting_policy_version__isnull', False), ('contract_liability_account__isnull', True), ('recognition_accounting_contract__isnull', True), ('recognition_policy_set_digest__isnull', True)), models.Q(('accounting_policy_version__isnull', True), ('contract_liability_account__isnull', False), ('recognition_accounting_contract', 'commercial-finalizer-v2-contract-liability'), ('recognition_policy_set_digest__isnull', False)), _connector='OR'), name='fin_commercial_accounting_contract_coherent'),
        ),
    ]
