# Generated by Django 4.0.7 on 2026-07-28 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_stockreservation_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_core', '0028_revenue_recognition_contract_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatePaymentAdjudication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('maker_approved', 'MAKER_APPROVED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('canceled', 'CANCELED')], db_index=True, default='open', max_length=24)),
                ('proposed_decision', models.CharField(blank=True, choices=[('accept', 'ACCEPT'), ('reject', 'REJECT')], max_length=16)),
                ('proposal_version', models.PositiveIntegerField(default=0)),
                ('maker_at', models.DateTimeField(blank=True, null=True)),
                ('maker_rationale', models.CharField(blank=True, max_length=1000)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checker_rationale', models.CharField(blank=True, max_length=1000)),
                ('decision', models.CharField(blank=True, choices=[('accept', 'ACCEPT'), ('reject', 'REJECT')], max_length=16)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_payment_adjudications', to='financial_core.paymentattempt')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_late_payment_adjudications', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='made_late_payment_adjudications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_payment_adjudications', to='shop.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_payment_adjudications', to='financial_core.payment')),
                ('review_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='late_payment_adjudication', to='financial_core.reviewcase')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_payment_adjudications', to='financial_core.paymenttransaction')),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='late_payment_adjudication', to='financial_core.verification')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionalRecognitionAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_reference', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('expected_payment_version', models.PositiveIntegerField()),
                ('evidence_hash', models.CharField(max_length=64)),
                ('authorization_fingerprint', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('authorized', 'AUTHORIZED'), ('applied', 'APPLIED')], db_index=True, default='authorized', max_length=16)),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('adjudication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_authorization', to='financial_core.latepaymentadjudication')),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptional_authorization', to='financial_core.financialallocation')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial_core.paymentattempt')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_exceptional_recognitions', to=settings.AUTH_USER_MODEL)),
                ('merchant_account_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial_core.merchantaccountversion')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial_core.payment')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='financial_core.paymenttransaction')),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exceptional_recognition_authorization', to='financial_core.verification')),
            ],
        ),
        migrations.AddIndex(
            model_name='latepaymentadjudication',
            index=models.Index(fields=['status', 'created_at'], name='fin_late_adj_queue'),
        ),
        migrations.AddIndex(
            model_name='latepaymentadjudication',
            index=models.Index(fields=['payment', 'status'], name='fin_late_adj_payment'),
        ),
        migrations.AddConstraint(
            model_name='latepaymentadjudication',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['open', 'maker_approved', 'approved', 'rejected', 'canceled'])), name='fin_late_adj_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='latepaymentadjudication',
            constraint=models.CheckConstraint(check=models.Q(('proposed_decision', ''), ('proposed_decision__in', ['accept', 'reject']), _connector='OR'), name='fin_late_adj_proposal_valid'),
        ),
        migrations.AddConstraint(
            model_name='latepaymentadjudication',
            constraint=models.CheckConstraint(check=models.Q(('decision', ''), ('decision__in', ['accept', 'reject']), _connector='OR'), name='fin_late_adj_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='latepaymentadjudication',
            constraint=models.CheckConstraint(check=models.Q(('checker__isnull', True), models.Q(('checker', django.db.models.expressions.F('maker')), _negated=True), _connector='OR'), name='fin_late_adj_maker_checker_distinct'),
        ),
        migrations.AddConstraint(
            model_name='latepaymentadjudication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('checked_at__isnull', True), ('checker__isnull', True), ('decision', ''), ('maker__isnull', True), ('maker_at__isnull', True), ('proposal_version', 0), ('proposed_decision', ''), ('status', 'open')), models.Q(('checked_at__isnull', True), ('checker__isnull', True), ('decision', ''), ('maker__isnull', False), ('maker_at__isnull', False), ('proposal_version__gt', 0), ('proposed_decision__in', ['accept', 'reject']), ('status', 'maker_approved')), models.Q(('checked_at__isnull', False), ('checker__isnull', False), ('decision__in', ['accept', 'reject']), ('maker__isnull', False), ('maker_at__isnull', False), ('proposal_version__gt', 0), ('proposed_decision__in', ['accept', 'reject']), ('status__in', ('approved', 'rejected'))), models.Q(('checked_at__isnull', False), ('status', 'canceled')), _connector='OR'), name='fin_late_adj_state_coherent'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalrecognitionauthorization',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='fin_exception_auth_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalrecognitionauthorization',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'IRR')), name='fin_exception_auth_currency_irr'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalrecognitionauthorization',
            constraint=models.CheckConstraint(check=models.Q(('provider_reference', ''), _negated=True), name='fin_exception_auth_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalrecognitionauthorization',
            constraint=models.CheckConstraint(check=models.Q(('evidence_hash', ''), _negated=True), name='fin_exception_auth_evidence_hash'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalrecognitionauthorization',
            constraint=models.CheckConstraint(check=models.Q(('authorization_fingerprint', ''), _negated=True), name='fin_exception_auth_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalrecognitionauthorization',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['authorized', 'applied'])), name='fin_exception_auth_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalrecognitionauthorization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('allocation__isnull', True), ('applied_at__isnull', True), ('status', 'authorized')), models.Q(('allocation__isnull', False), ('applied_at__isnull', False), ('status', 'applied')), _connector='OR'), name='fin_exception_auth_application_coherent'),
        ),
    ]
