# Generated by Codex on 2026-06-13

from django.db import migrations, models


TRACKING_CODE_PREFIX = "FX"
TRACKING_CODE_START = 1001


def next_tracking_code(used_codes):
    number = TRACKING_CODE_START
    while True:
        code = f"{TRACKING_CODE_PREFIX}-{number}"
        if code not in used_codes:
            used_codes.add(code)
            return code
        number += 1


def populate_public_tracking_codes(apps, schema_editor):
    IssueReport = apps.get_model("issue", "IssueReport")
    used_codes = set(
        IssueReport.objects.exclude(public_tracking_code__isnull=True)
        .exclude(public_tracking_code="")
        .values_list("public_tracking_code", flat=True)
    )

    for issue_report in IssueReport.objects.filter(public_tracking_code__isnull=True).order_by("id"):
        issue_report.public_tracking_code = next_tracking_code(used_codes)
        issue_report.save(update_fields=["public_tracking_code"])

    for issue_report in IssueReport.objects.filter(public_tracking_code="").order_by("id"):
        issue_report.public_tracking_code = next_tracking_code(used_codes)
        issue_report.save(update_fields=["public_tracking_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0014_alter_issuereport_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuereport",
            name="public_tracking_code",
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(populate_public_tracking_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="issuereport",
            name="public_tracking_code",
            field=models.CharField(blank=True, editable=False, max_length=16, unique=True),
        ),
    ]
