# Generated by Django 4.0.7 on 2026-07-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_stockreservation_order_and_more'),
        ('digital_products', '0004_digitalinventoryreservation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='digitalinventoryreservation',
            name='digital_res_state_valid',
        ),
        migrations.AddField(
            model_name='digitalinventoryreservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_inventory_reservations', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='digitalinventoryreservation',
            name='state',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('payment_hold', 'PAYMENT_HOLD'), ('held_for_review', 'HELD_FOR_REVIEW'), ('consumed', 'CONSUMED'), ('released', 'RELEASED'), ('expired', 'EXPIRED')], default='active', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='digitalinventoryreservation',
            constraint=models.CheckConstraint(check=models.Q(('state__in', ['active', 'payment_hold', 'held_for_review', 'consumed', 'released', 'expired'])), name='digital_res_state_valid'),
        ),
    ]
