# Generated by Django 4.0.7 on 2026-07-17 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_stockreservation_order_and_more'),
        ('financial_core', '0015_postgresql_finalized_projection_guards'),
        ('product', '0020_deliveredversion_product_commerce_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital_products', '0005_remove_digitalinventoryreservation_digital_res_state_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalFulfillmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'QUEUED'), ('waiting_customer', 'WAITING_CUSTOMER'), ('ready_for_staff', 'READY_FOR_STAFF'), ('in_progress', 'IN_PROGRESS'), ('waiting_confirmation', 'WAITING_CONFIRMATION'), ('completed', 'COMPLETED'), ('exception', 'EXCEPTION')], default='queued', max_length=24)),
                ('waiting_reason', models.CharField(blank=True, choices=[('contact_required', 'CONTACT_REQUIRED'), ('method_confirmation_required', 'METHOD_CONFIRMATION_REQUIRED'), ('appointment_required', 'APPOINTMENT_REQUIRED'), ('waiting_for_console', 'WAITING_FOR_CONSOLE'), ('remote_customer_action_required', 'REMOTE_CUSTOMER_ACTION_REQUIRED'), ('customer_confirmation_required', 'CUSTOMER_CONFIRMATION_REQUIRED'), ('additional_information_required', 'ADDITIONAL_INFORMATION_REQUIRED')], max_length=40, null=True)),
                ('current_fulfillment_method', models.CharField(choices=[('in_store', 'IN_STORE'), ('remote', 'REMOTE')], max_length=16)),
                ('internal_reference', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_fulfillment_items', to='shop.deliverydata')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_digital_fulfillments', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='financial_core.digitalfulfillmentobligation')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('purchased', 'PURCHASED'), ('bonus', 'BONUS')], max_length=16)),
                ('completion_source', models.CharField(choices=[('staff_installed', 'STAFF_INSTALLED'), ('customer_confirmed', 'CUSTOMER_CONFIRMED'), ('staff_verified_remote', 'STAFF_VERIFIED_REMOTE')], max_length=24)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fallback_title', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('recorded', 'RECORDED'), ('corrected', 'CORRECTED'), ('removed', 'REMOVED')], default='recorded', max_length=16)),
                ('correction_reason', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='digital_products.installedgamerecord')),
                ('delivered_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installation_records', to='product.deliveredversion')),
                ('fulfillment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_games', to='digital_products.digitalfulfillmentitem')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_installation_records', to='product.product')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_installed_game_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FulfillmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('status_changed', 'STATUS_CHANGED'), ('operator_assigned', 'OPERATOR_ASSIGNED'), ('customer_contact_attempted', 'CUSTOMER_CONTACT_ATTEMPTED'), ('customer_contacted', 'CUSTOMER_CONTACTED'), ('method_changed', 'METHOD_CHANGED'), ('console_received', 'CONSOLE_RECEIVED'), ('work_started', 'WORK_STARTED'), ('installation_performed', 'INSTALLATION_PERFORMED'), ('remote_handling_performed', 'REMOTE_HANDLING_PERFORMED'), ('customer_action_requested', 'CUSTOMER_ACTION_REQUESTED'), ('customer_confirmed', 'CUSTOMER_CONFIRMED'), ('staff_verified', 'STAFF_VERIFIED'), ('failure_recorded', 'FAILURE_RECORDED'), ('retry_started', 'RETRY_STARTED'), ('note_added', 'NOTE_ADDED'), ('bonus_recorded', 'BONUS_RECORDED'), ('provisioned', 'PROVISIONED')], max_length=40)),
                ('actor_type', models.CharField(choices=[('customer', 'CUSTOMER'), ('staff', 'STAFF'), ('system', 'SYSTEM')], max_length=16)),
                ('visibility', models.CharField(choices=[('customer_safe', 'CUSTOMER_SAFE'), ('internal', 'INTERNAL')], max_length=16)),
                ('previous_status', models.CharField(blank=True, choices=[('queued', 'QUEUED'), ('waiting_customer', 'WAITING_CUSTOMER'), ('ready_for_staff', 'READY_FOR_STAFF'), ('in_progress', 'IN_PROGRESS'), ('waiting_confirmation', 'WAITING_CONFIRMATION'), ('completed', 'COMPLETED'), ('exception', 'EXCEPTION')], max_length=24, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('queued', 'QUEUED'), ('waiting_customer', 'WAITING_CUSTOMER'), ('ready_for_staff', 'READY_FOR_STAFF'), ('in_progress', 'IN_PROGRESS'), ('waiting_confirmation', 'WAITING_CONFIRMATION'), ('completed', 'COMPLETED'), ('exception', 'EXCEPTION')], max_length=24, null=True)),
                ('waiting_reason', models.CharField(blank=True, choices=[('contact_required', 'CONTACT_REQUIRED'), ('method_confirmation_required', 'METHOD_CONFIRMATION_REQUIRED'), ('appointment_required', 'APPOINTMENT_REQUIRED'), ('waiting_for_console', 'WAITING_FOR_CONSOLE'), ('remote_customer_action_required', 'REMOTE_CUSTOMER_ACTION_REQUIRED'), ('customer_confirmation_required', 'CUSTOMER_CONFIRMATION_REQUIRED'), ('additional_information_required', 'ADDITIONAL_INFORMATION_REQUIRED')], max_length=40, null=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('idempotency_key', models.UUIDField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_fulfillment_activities', to=settings.AUTH_USER_MODEL)),
                ('fulfillment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='digital_products.digitalfulfillmentitem')),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_fulfillment', 'PENDING_FULFILLMENT'), ('active', 'ACTIVE'), ('under_review', 'UNDER_REVIEW'), ('ended', 'ENDED')], default='pending_fulfillment', max_length=24)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('full_refund', 'FULL_REFUND'), ('permanent_cancellation', 'PERMANENT_CANCELLATION')], max_length=32, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_entitlements', to=settings.AUTH_USER_MODEL)),
                ('fulfillment_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement', to='digital_products.digitalfulfillmentitem')),
                ('obligation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement', to='financial_core.digitalfulfillmentobligation')),
            ],
        ),
        migrations.AddIndex(
            model_name='installedgamerecord',
            index=models.Index(fields=['fulfillment_item', 'created_at'], name='digital_installed_timeline'),
        ),
        migrations.AddConstraint(
            model_name='installedgamerecord',
            constraint=models.CheckConstraint(check=models.Q(('classification__in', ['purchased', 'bonus'])), name='digital_installed_class_valid'),
        ),
        migrations.AddConstraint(
            model_name='installedgamerecord',
            constraint=models.CheckConstraint(check=models.Q(('completion_source__in', ['staff_installed', 'customer_confirmed', 'staff_verified_remote'])), name='digital_installed_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='installedgamerecord',
            constraint=models.CheckConstraint(check=models.Q(('state__in', ['recorded', 'corrected', 'removed'])), name='digital_installed_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='installedgamerecord',
            constraint=models.CheckConstraint(check=models.Q(('game__isnull', False), models.Q(('fallback_title', ''), _negated=True), _connector='OR'), name='digital_installed_identity_required'),
        ),
        migrations.AddConstraint(
            model_name='installedgamerecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('classification', 'purchased'), _negated=True), models.Q(('delivered_version__isnull', False), ('game__isnull', False)), _connector='OR'), name='digital_installed_purchased_identity'),
        ),
        migrations.AddConstraint(
            model_name='installedgamerecord',
            constraint=models.CheckConstraint(check=models.Q(('completion_source', 'customer_confirmed'), ('operator__isnull', False), _connector='OR'), name='digital_installed_staff_operator'),
        ),
        migrations.AddConstraint(
            model_name='installedgamerecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('correction_reason', ''), ('corrects__isnull', True), ('state', 'recorded')), models.Q(('corrects__isnull', False), ('state__in', ('corrected', 'removed')), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='digital_installed_correction_fields'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentactivity',
            index=models.Index(fields=['fulfillment_item', 'created_at'], name='digital_activity_timeline'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentactivity',
            constraint=models.CheckConstraint(check=models.Q(('activity_type__in', ['status_changed', 'operator_assigned', 'customer_contact_attempted', 'customer_contacted', 'method_changed', 'console_received', 'work_started', 'installation_performed', 'remote_handling_performed', 'customer_action_requested', 'customer_confirmed', 'staff_verified', 'failure_recorded', 'retry_started', 'note_added', 'bonus_recorded', 'provisioned'])), name='digital_activity_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentactivity',
            constraint=models.CheckConstraint(check=models.Q(('actor_type__in', ['customer', 'staff', 'system'])), name='digital_activity_actor_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentactivity',
            constraint=models.CheckConstraint(check=models.Q(('visibility__in', ['customer_safe', 'internal'])), name='digital_activity_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentactivity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('actor__isnull', True), ('actor_type', 'system')), models.Q(('actor__isnull', False), ('actor_type__in', ('customer', 'staff'))), _connector='OR'), name='digital_activity_actor_presence'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='digital_activity_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['customer', 'status'], name='digital_entitlement_customer'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending_fulfillment', 'active', 'under_review', 'ended'])), name='digital_entitlement_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activated_at__isnull', True), ('end_reason__isnull', True), ('ended_at__isnull', True), ('status', 'pending_fulfillment')), models.Q(('activated_at__isnull', False), ('end_reason__isnull', True), ('ended_at__isnull', True), ('status__in', ('active', 'under_review'))), models.Q(('end_reason__isnull', False), ('ended_at__isnull', False), ('status', 'ended')), _connector='OR'), name='digital_entitlement_lifecycle_fields'),
        ),
        migrations.AddIndex(
            model_name='digitalfulfillmentitem',
            index=models.Index(fields=['status', 'waiting_reason'], name='digital_fulfill_queue'),
        ),
        migrations.AddIndex(
            model_name='digitalfulfillmentitem',
            index=models.Index(fields=['assigned_operator', 'status'], name='digital_fulfill_operator'),
        ),
        migrations.AddConstraint(
            model_name='digitalfulfillmentitem',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['queued', 'waiting_customer', 'ready_for_staff', 'in_progress', 'waiting_confirmation', 'completed', 'exception'])), name='digital_fulfill_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='digitalfulfillmentitem',
            constraint=models.CheckConstraint(check=models.Q(('current_fulfillment_method__in', ['in_store', 'remote'])), name='digital_fulfill_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='digitalfulfillmentitem',
            constraint=models.CheckConstraint(check=models.Q(('waiting_reason__isnull', True), ('waiting_reason__in', ['contact_required', 'method_confirmation_required', 'appointment_required', 'waiting_for_console', 'remote_customer_action_required', 'customer_confirmation_required', 'additional_information_required']), _connector='OR'), name='digital_fulfill_wait_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='digitalfulfillmentitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='digital_fulfill_completed_time'),
        ),
    ]
