# Generated by Django 4.0.7 on 2026-07-17 14:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0007_postgresql_fulfillment_ownership_guards'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fulfillmentactivity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activity_type', 'status_changed'), ('new_status__isnull', False)), models.Q(models.Q(('activity_type', 'status_changed'), _negated=True), ('new_status__isnull', True), ('previous_status__isnull', True)), _connector='OR'), name='digital_activity_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentactivity',
            constraint=models.CheckConstraint(check=models.Q(('previous_status__isnull', True), ('new_status__isnull', True), models.Q(('previous_status', django.db.models.expressions.F('new_status')), _negated=True), _connector='OR'), name='digital_activity_status_changed'),
        ),
    ]
