# Generated by Django 4.0.7 on 2026-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0008_fulfillmentactivity_digital_activity_status_fields_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='installedgamerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('classification', 'purchased'), ('state', 'recorded')), fields=('fulfillment_item',), name='digital_one_current_purchased_evidence'),
        ),
    ]
