# Generated by Django 4.0.7 on 2026-07-28 09:38

from django.db import migrations, models
from django.db.models import Count
import django.db.models.deletion


def assert_current_reservation_cardinality(apps, schema_editor):
    reservation = apps.get_model("digital_products", "DigitalInventoryReservation")
    conflicts = list(
        reservation.objects.filter(state__in=("active", "payment_hold", "held_for_review"))
        .values("checkout_line_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .order_by("checkout_line_id")
        .values_list("checkout_line_id", flat=True)[:20]
    )
    if conflicts:
        raise RuntimeError(
            "Cannot install current Digital reservation uniqueness; "
            f"conflicting CheckoutLine ids: {conflicts}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('financial_core', '0029_latepaymentadjudication_and_more'),
        ('shop', '0020_stockreservation_order_and_more'),
        ('digital_products', '0012_upcoming_game_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalinventoryreservation',
            name='recovery_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_inventory_reservations', to='financial_core.exceptionalrecognitionauthorization'),
        ),
        migrations.AlterField(
            model_name='digitalinventoryreservation',
            name='checkout_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_inventory_reservations', to='shop.checkoutline'),
        ),
        migrations.AddConstraint(
            model_name='digitalinventoryreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('recovery_authorization__isnull', True)), fields=('checkout_line',), name='digital_original_reservation_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='digitalinventoryreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('recovery_authorization__isnull', False)), fields=('recovery_authorization', 'checkout_line'), name='digital_recovery_auth_line_uniq'),
        ),
        migrations.RunPython(assert_current_reservation_cardinality, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='digitalinventoryreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('active', 'payment_hold', 'held_for_review'))), fields=('checkout_line',), name='digital_current_reservation_line_uniq'),
        ),
    ]
