# Generated by Django 4.0.7 on 2026-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0013_digitalinventoryreservation_recovery_authorization_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='digitalgamereleasemetadata',
            name='digital_game_preorder_disabled_v1',
        ),
        migrations.RemoveConstraint(
            model_name='digitalgamereleasemetadata',
            name='digital_game_preorder_status_requires_enablement',
        ),
        migrations.AddConstraint(
            model_name='digitalgamereleasemetadata',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('preorder_enabled', True), ('upcoming_status', 'PREORDER_OPEN')), models.Q(models.Q(('upcoming_status', 'PREORDER_OPEN'), _negated=True), ('preorder_enabled', False)), _connector='OR'), name='digital_game_preorder_state_coherent_v1'),
        ),
    ]
