# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_product_foundation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
