from django.urls import path

from cheatgame.digital_products.public_catalog_apis import (
    PublicDigitalGameDetailApi,
    PublicDigitalGameListApi,
)
from cheatgame.digital_products.customer_cart_apis import (
    CustomerDigitalCartFulfillmentMethodApi,
    CustomerDigitalCartItemCreateApi,
    CustomerDigitalCartItemDeleteApi,
)
from cheatgame.digital_products.customer_checkout_apis import (
    CustomerDigitalCheckoutActiveApi,
    CustomerDigitalCheckoutCancelApi,
    CustomerDigitalCheckoutDetailApi,
    CustomerDigitalCheckoutPrepareApi,
)
from cheatgame.digital_products.customer_payment_apis import (
    CustomerDigitalPaymentRequestApi,
    CustomerDigitalPaymentStatusApi,
)
from cheatgame.digital_products.admin_fulfillment_apis import (
    AssignableOperatorDirectoryApi,
    DigitalFulfillmentCommandApi,
    DigitalFulfillmentDetailApi,
    DigitalFulfillmentOptionsApi,
    DigitalFulfillmentQueueApi,
)
from cheatgame.digital_products.admin_catalog_apis import (
    ActivateDigitalProductApi,
    AdjustOfferStockApi,
    AdminCatalogGameDetailApi,
    AdminCatalogGameListApi,
    ArchiveDeliveredVersionApi,
    ChangeOfferStateApi,
    CreateDeliveredVersionApi,
    CreateDigitalOfferApi,
    DeactivateDigitalProductApi,
    MakeOfferStockIndependentApi,
    ShareOfferStockApi,
    UpdateOfferPriceApi,
)


app_name = "digital-products"

urlpatterns = [
    path("catalog/games/", PublicDigitalGameListApi.as_view(), name="public-game-list"),
    path("catalog/games/<str:slug>/", PublicDigitalGameDetailApi.as_view(), name="public-game-detail"),
    path(
        "customer/cart/items/",
        CustomerDigitalCartItemCreateApi.as_view(),
        name="customer-cart-item-add",
    ),
    path(
        "customer/cart/items/<int:cart_item_id>/",
        CustomerDigitalCartItemDeleteApi.as_view(),
        name="customer-cart-item-remove",
    ),
    path(
        "customer/cart/items/<int:cart_item_id>/fulfillment-method/",
        CustomerDigitalCartFulfillmentMethodApi.as_view(),
        name="customer-cart-fulfillment-method-change",
    ),
    path(
        "customer/checkout/prepare/",
        CustomerDigitalCheckoutPrepareApi.as_view(),
        name="customer-checkout-prepare",
    ),
    path(
        "customer/checkout/active/",
        CustomerDigitalCheckoutActiveApi.as_view(),
        name="customer-checkout-active",
    ),
    path(
        "customer/checkout/<uuid:checkout_id>/",
        CustomerDigitalCheckoutDetailApi.as_view(),
        name="customer-checkout-detail",
    ),
    path(
        "customer/checkout/<uuid:checkout_id>/cancel/",
        CustomerDigitalCheckoutCancelApi.as_view(),
        name="customer-checkout-cancel",
    ),
    path(
        "customer/checkout/<uuid:checkout_id>/payment/request/",
        CustomerDigitalPaymentRequestApi.as_view(),
        name="customer-payment-request",
    ),
    path(
        "customer/checkout/<uuid:checkout_id>/payment/",
        CustomerDigitalPaymentStatusApi.as_view(),
        name="customer-payment-status",
    ),
    path(
        "admin/catalog/games/",
        AdminCatalogGameListApi.as_view(),
        name="admin-catalog-game-list",
    ),
    path(
        "admin/catalog/games/<int:product_id>/",
        AdminCatalogGameDetailApi.as_view(),
        name="admin-catalog-game-detail",
    ),
    path(
        "admin/catalog/games/<int:product_id>/versions/",
        CreateDeliveredVersionApi.as_view(),
        name="admin-catalog-version-create",
    ),
    path(
        "admin/catalog/versions/<int:version_id>/archive/",
        ArchiveDeliveredVersionApi.as_view(),
        name="admin-catalog-version-archive",
    ),
    path(
        "admin/catalog/games/<int:product_id>/offers/",
        CreateDigitalOfferApi.as_view(),
        name="admin-catalog-offer-create",
    ),
    path(
        "admin/catalog/offers/<int:offer_id>/price/",
        UpdateOfferPriceApi.as_view(),
        name="admin-catalog-offer-price",
    ),
    path(
        "admin/catalog/offers/<int:offer_id>/state/",
        ChangeOfferStateApi.as_view(),
        name="admin-catalog-offer-state",
    ),
    path(
        "admin/catalog/offers/<int:offer_id>/stock-adjustments/",
        AdjustOfferStockApi.as_view(),
        name="admin-catalog-offer-stock-adjustment",
    ),
    path(
        "admin/catalog/offers/<int:offer_id>/share-stock/",
        ShareOfferStockApi.as_view(),
        name="admin-catalog-offer-share-stock",
    ),
    path(
        "admin/catalog/offers/<int:offer_id>/independent-stock/",
        MakeOfferStockIndependentApi.as_view(),
        name="admin-catalog-offer-independent-stock",
    ),
    path(
        "admin/catalog/games/<int:product_id>/activate-digital/",
        ActivateDigitalProductApi.as_view(),
        name="admin-catalog-activate-digital",
    ),
    path(
        "admin/catalog/games/<int:product_id>/deactivate-digital/",
        DeactivateDigitalProductApi.as_view(),
        name="admin-catalog-deactivate-digital",
    ),
    path(
        "admin/fulfillments/",
        DigitalFulfillmentQueueApi.as_view(),
        name="admin-fulfillment-queue",
    ),
    path(
        "admin/fulfillments/<uuid:fulfillment_id>/",
        DigitalFulfillmentDetailApi.as_view(),
        name="admin-fulfillment-detail",
    ),
    path(
        "admin/fulfillments/<uuid:fulfillment_id>/<str:command>/",
        DigitalFulfillmentCommandApi.as_view(),
        name="admin-fulfillment-command",
    ),
    path(
        "admin/operators/",
        AssignableOperatorDirectoryApi.as_view(),
        name="admin-fulfillment-operators",
    ),
    path(
        "admin/fulfillment-options/",
        DigitalFulfillmentOptionsApi.as_view(),
        name="admin-fulfillment-options",
    ),
]
