# Generated by Codex on 2026-06-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0010_alter_cartitem_price_alter_discount_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(db_index=True, default="fake", max_length=50)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "CREATED"),
                            ("pending", "PENDING"),
                            ("callback_received", "CALLBACK_RECEIVED"),
                            ("paid", "PAID"),
                            ("failed", "FAILED"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=32,
                    ),
                ),
                ("gateway_authority", models.CharField(blank=True, max_length=128, null=True)),
                ("gateway_ref_id", models.CharField(blank=True, max_length=128, null=True)),
                ("gateway_trace_no", models.CharField(blank=True, max_length=128, null=True)),
                ("gateway_payment_url", models.URLField(blank=True, max_length=500)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("callback_payload", models.JSONField(blank=True, default=dict)),
                ("verify_payload", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="shop.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["order", "status"], name="shop_paymen_order_i_0c1da4_idx"),
                    models.Index(fields=["user", "status"], name="shop_paymen_user_id_ea36a1_idx"),
                    models.Index(fields=["provider", "gateway_authority"], name="shop_paymen_provide_91f073_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_authority__isnull", False)),
                fields=("provider", "gateway_authority"),
                name="unique_payment_provider_authority",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gateway_ref_id__isnull", False)),
                fields=("provider", "gateway_ref_id"),
                name="unique_payment_provider_ref_id",
            ),
        ),
    ]
