# Generated by Codex on 2026-06-11

import uuid

from django.db import migrations, models


def populate_public_tracking_codes(apps, schema_editor):
    Order = apps.get_model("shop", "Order")
    for order in Order.objects.filter(public_tracking_code__isnull=True):
        while True:
            code = f"CH-{uuid.uuid4().hex[:10].upper()}"
            if not Order.objects.filter(public_tracking_code=code).exists():
                break
        order.public_tracking_code = code
        order.save(update_fields=["public_tracking_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_remove_deliverydata_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="public_tracking_code",
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(populate_public_tracking_codes, migrations.RunPython.noop),
    ]
