# Generated by Django 4.0.7 on 2026-07-12 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_category_name_not_globally_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_alter_deliverydata_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_checkout_uuid', models.UUIDField()),
                ('cart_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('checkout_draft', 'CHECKOUT_DRAFT'), ('pending_payment', 'PENDING_PAYMENT'), ('paid', 'PAID'), ('requires_manual_review', 'REQUIRES_MANUAL_REVIEW'), ('canceled', 'CANCELED'), ('expired', 'EXPIRED')], db_index=True, default='checkout_draft', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('maximum_expires_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('manual_review_reason', models.CharField(blank=True, choices=[('amount_mismatch', 'AMOUNT_MISMATCH'), ('stock_conflict', 'STOCK_CONFLICT'), ('delivery_conflict', 'DELIVERY_CONFLICT'), ('discount_conflict', 'DISCOUNT_CONFLICT'), ('provider_state_unclear', 'PROVIDER_STATE_UNCLEAR'), ('finalization_error', 'FINALIZATION_ERROR'), ('late_payment_after_expiry', 'LATE_PAYMENT_AFTER_EXPIRY'), ('unknown', 'UNKNOWN')], max_length=40, null=True)),
                ('manual_review_message', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_cart_item_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.IntegerField()),
                ('variation_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('variation_name', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_original_price', models.DecimalField(decimal_places=0, max_digits=16)),
                ('unit_payable_price', models.DecimalField(decimal_places=0, max_digits=16)),
                ('quantity', models.PositiveIntegerField()),
                ('line_original_total', models.DecimalField(decimal_places=0, max_digits=16)),
                ('line_payable_total', models.DecimalField(decimal_places=0, max_digits=16)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.checkout')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='lock_reason',
            field=models.CharField(blank=True, choices=[('checkout_in_progress', 'CHECKOUT_IN_PROGRESS'), ('payment_in_progress', 'PAYMENT_IN_PROGRESS'), ('manual_review', 'MANUAL_REVIEW'), ('admin', 'ADMIN')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lock_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.CharField(choices=[('open', 'OPEN'), ('locked', 'LOCKED')], db_index=True, default='open', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_started', 'NOT_STARTED'), ('processing', 'PROCESSING'), ('sending', 'SENDING'), ('delivered', 'DELIVERED'), ('canceled', 'CANCELED')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='manual_review_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='manual_review_reason',
            field=models.CharField(blank=True, choices=[('amount_mismatch', 'AMOUNT_MISMATCH'), ('stock_conflict', 'STOCK_CONFLICT'), ('delivery_conflict', 'DELIVERY_CONFLICT'), ('discount_conflict', 'DISCOUNT_CONFLICT'), ('provider_state_unclear', 'PROVIDER_STATE_UNCLEAR'), ('finalization_error', 'FINALIZATION_ERROR'), ('late_payment_after_expiry', 'LATE_PAYMENT_AFTER_EXPIRY'), ('unknown', 'UNKNOWN')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_reported_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='result_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verification_claim_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verification_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('callback_received', 'CALLBACK_RECEIVED'), ('verifying', 'VERIFYING'), ('paid', 'PAID'), ('failed', 'FAILED'), ('requires_manual_review', 'REQUIRES_MANUAL_REVIEW')], db_index=True, default='created', max_length=32),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('active', 'ACTIVE'), ('consumed', 'CONSUMED'), ('released', 'RELEASED')], db_index=True, default='active', max_length=16)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='shop.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('checkout_draft_created', 'CHECKOUT_DRAFT_CREATED'), ('checkout_draft_reused', 'CHECKOUT_DRAFT_REUSED'), ('cart_locked', 'CART_LOCKED'), ('cart_unlocked', 'CART_UNLOCKED'), ('address_selected', 'ADDRESS_SELECTED'), ('shipping_selected', 'SHIPPING_SELECTED'), ('schedule_selected', 'SCHEDULE_SELECTED'), ('payment_requested', 'PAYMENT_REQUESTED'), ('gateway_callback_received', 'GATEWAY_CALLBACK_RECEIVED'), ('payment_verification_started', 'PAYMENT_VERIFICATION_STARTED'), ('payment_verified', 'PAYMENT_VERIFIED'), ('payment_failed', 'PAYMENT_FAILED'), ('stock_reservation_created', 'STOCK_RESERVATION_CREATED'), ('stock_reservation_released', 'STOCK_RESERVATION_RELEASED'), ('stock_reservation_consumed', 'STOCK_RESERVATION_CONSUMED'), ('fulfillment_finalization_succeeded', 'FULFILLMENT_FINALIZATION_SUCCEEDED'), ('manual_review_required', 'MANUAL_REVIEW_REQUIRED'), ('checkout_expired', 'CHECKOUT_EXPIRED'), ('checkout_canceled', 'CHECKOUT_CANCELED')], db_index=True, max_length=64)),
                ('actor_type', models.CharField(choices=[('customer', 'CUSTOMER'), ('system', 'SYSTEM'), ('gateway', 'GATEWAY'), ('admin', 'ADMIN'), ('support', 'SUPPORT')], max_length=16)),
                ('actor_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('idempotency_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='shop.checkout')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_events', to='shop.order')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commerce_events', to='shop.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutShippingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=32)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('full_address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_method_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('delivery_method_name', models.CharField(blank=True, max_length=200)),
                ('delivery_cost', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('schedule_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('schedule_start', models.DateTimeField(blank=True, null=True)),
                ('schedule_end', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_snapshot', to='shop.checkout')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutLineAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attachment_type', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=16)),
                ('quantity_basis', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shop.checkoutline')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='shop.cart'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='active_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_carts', to='shop.checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.checkout'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='shop.checkout'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['state', 'expires_at'], name='shop_res_state_expires'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='stock_reservation_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('checkout', 'product'), name='uniq_active_reservation_product'),
        ),
        migrations.AddIndex(
            model_name='commerceevent',
            index=models.Index(fields=['checkout', 'created_at'], name='shop_event_checkout_created'),
        ),
        migrations.AddIndex(
            model_name='commerceevent',
            index=models.Index(fields=['order', 'created_at'], name='shop_event_order_created'),
        ),
        migrations.AddIndex(
            model_name='commerceevent',
            index=models.Index(fields=['payment_transaction', 'created_at'], name='shop_event_payment_created'),
        ),
        migrations.AddIndex(
            model_name='commerceevent',
            index=models.Index(fields=['event_type', 'created_at'], name='shop_event_type_created'),
        ),
        migrations.AddIndex(
            model_name='commerceevent',
            index=models.Index(fields=['idempotency_reference'], name='shop_event_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='checkoutshippingsnapshot',
            constraint=models.CheckConstraint(check=models.Q(('delivery_cost__gte', 0)), name='checkout_shipping_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='checkoutlineattachment',
            constraint=models.CheckConstraint(check=models.Q(('quantity_basis__gt', 0)), name='checkout_attachment_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='checkoutlineattachment',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='checkout_attachment_unit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='checkoutlineattachment',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='checkout_attachment_total_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='checkoutline',
            index=models.Index(fields=['checkout', 'product_id'], name='shop_line_checkout_product'),
        ),
        migrations.AddConstraint(
            model_name='checkoutline',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='checkout_line_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='checkoutline',
            constraint=models.CheckConstraint(check=models.Q(('unit_original_price__gte', 0)), name='checkout_line_original_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='checkoutline',
            constraint=models.CheckConstraint(check=models.Q(('unit_payable_price__gte', 0)), name='checkout_line_payable_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='checkoutline',
            constraint=models.CheckConstraint(check=models.Q(('line_original_total__gte', 0)), name='checkout_line_total_orig_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='checkoutline',
            constraint=models.CheckConstraint(check=models.Q(('line_payable_total__gte', 0)), name='checkout_line_total_pay_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['user', 'status', '-created_at'], name='shop_co_user_stat_created'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['status', 'expires_at'], name='shop_co_status_expires'),
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(fields=('user', 'client_checkout_uuid'), name='uniq_checkout_user_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(condition=models.Q(('cart__isnull', False), ('status__in', ('checkout_draft', 'pending_payment', 'requires_manual_review'))), fields=('cart',), name='uniq_active_checkout_per_cart'),
        ),
    ]
