# Generated by Django 4.0.7 on 2026-07-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_checkoutline_commerce_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='commerceevent',
            name='event_type',
            field=models.CharField(choices=[('checkout_draft_created', 'CHECKOUT_DRAFT_CREATED'), ('checkout_draft_reused', 'CHECKOUT_DRAFT_REUSED'), ('cart_locked', 'CART_LOCKED'), ('cart_unlocked', 'CART_UNLOCKED'), ('address_selected', 'ADDRESS_SELECTED'), ('shipping_selected', 'SHIPPING_SELECTED'), ('schedule_selected', 'SCHEDULE_SELECTED'), ('payment_requested', 'PAYMENT_REQUESTED'), ('gateway_callback_received', 'GATEWAY_CALLBACK_RECEIVED'), ('payment_verification_started', 'PAYMENT_VERIFICATION_STARTED'), ('payment_verified', 'PAYMENT_VERIFIED'), ('payment_failed', 'PAYMENT_FAILED'), ('stock_reservation_created', 'STOCK_RESERVATION_CREATED'), ('stock_reservation_released', 'STOCK_RESERVATION_RELEASED'), ('stock_reservation_consumed', 'STOCK_RESERVATION_CONSUMED'), ('fulfillment_finalization_succeeded', 'FULFILLMENT_FINALIZATION_SUCCEEDED'), ('manual_review_required', 'MANUAL_REVIEW_REQUIRED'), ('checkout_expired', 'CHECKOUT_EXPIRED'), ('checkout_canceled', 'CHECKOUT_CANCELED'), ('order_placed', 'ORDER_PLACED'), ('payment_obligation_created', 'PAYMENT_OBLIGATION_CREATED')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='state',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('payment_hold', 'PAYMENT_HOLD'), ('review_hold', 'REVIEW_HOLD'), ('consumed', 'CONSUMED'), ('released', 'RELEASED')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout__isnull', False)), fields=('checkout',), name='uniq_order_per_checkout'),
        ),
    ]
