name: Deploy Backend Staging to Liara
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Deploy backend staging
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@9
          liara deploy --app="backend-cheatsgame-staging" --api-token="$LIARA_TOKEN" --no-app-logs --port 7000
